# generated by datamodel-codegen:
#   filename:  inference-driver.yaml

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class ToolChoice(StrEnum):
    """
    `none`, `auto`, `required`, or an object naming one
    function. Passed through.

    """

    none = 'none'
    auto = 'auto'
    required = 'required'


class Role(StrEnum):
    """
    The speaker of a single message in a conversation. Matches the
    OpenAI / Anthropic chat roles so adapters never re-shape on a hop.

    """

    system = 'system'
    user = 'user'
    assistant = 'assistant'
    tool = 'tool'


class TextContentPart(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['text']
    text: str


class Detail(StrEnum):
    """
    Explicit high/low processing modes are not supported.
    """

    auto = 'auto'


class ImageUrl(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    url: str = Field(
        ...,
        description='Inline base64 PNG or JPEG data URL. No remote references.',
        max_length=6990531,
    )
    detail: Detail | None = Field(
        None, description='Explicit high/low processing modes are not supported.'
    )


class ImageContentPart(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['image_url']
    image_url: ImageUrl


class BackendKind(StrEnum):
    """
    Which wire protocol an inference-driver instance speaks to its
    backend. Reported by the driver's `/v1/info` so the gateway can
    log it and the UI can render a label.

    `openai_compat_http` covers every local engine we care about
    (llama.cpp's `llama-server`, vLLM, LM Studio, Ollama) as well as
    hosted OpenAI-compatible services — the protocol is shared even
    though the providers are not, so `DriverInfo.provider` is what
    distinguishes them. `claude_code_cli` and `codex_cli` shell out
    to the respective CLIs, which is how a subscription the operator
    already pays for becomes just another backend.

    `systemone_http` speaks the TypeSafe System One decision
    protocol (`POST /v1/systemone`: a state and named typed
    questions, answered with structured probabilities rather than
    text) — a supervised Kev runtime, another System One-compatible
    server, or TypeSafe's own hosted endpoint, distinguished by
    `DriverInfo.provider` exactly as the chat protocols are. A
    driver on this protocol serves decisions and not chat; see
    `Capabilities.chatCapable`.

    """

    anthropic_api = 'anthropic_api'
    openai_api = 'openai_api'
    claude_code_cli = 'claude_code_cli'
    codex_cli = 'codex_cli'
    openai_compat_http = 'openai_compat_http'
    systemone_http = 'systemone_http'


class ComponentKind(StrEnum):
    """
    Which Eugene Plexus component class a topology entry
    represents. Lives in `common.yaml` because more than one
    component references it: the agent's `/v1/components`, and
    (via `ConfigField.componentKindHint`) any component declaring
    a config field that points at a peer of a specific kind.

    A component is a **Eugene Plexus process**. Engine processes
    are not components and are not named here — they are runtimes,
    declared separately on the agent, because a third-party
    binary shares none of a component's declarative shape (no
    module, no config trio, no service token). See the agent's
    `GET /v1/runtimes`.

    `control` is the trust root, node registry, install-wide
    topology and UI host — exactly one active, plus warm standbys.
    `gateway` is the one OpenAI-compatible front door and there is
    exactly one. `inference-driver` instances are the per-backend
    wrappers and there are N — one per backend, wherever that
    backend lives. `library` scans the operator's model
    directories and holds per-model launch profiles; there is
    exactly one, and it is deliberately not in the request path.

    **The agent is not in this list**, for the same reason engine
    runtimes are not: it supervises, it is not supervised. Its
    lifecycle belongs to the platform — a systemd unit, a container
    entrypoint — not to a topology entry. `control` *is* in the list
    precisely because the agent on its host supervises it like
    anything else, which is what stops the control root needing a
    second copy of the supervision machinery.

    """

    control = 'control'
    gateway = 'gateway'
    inference_driver = 'inference-driver'
    library = 'library'


class ComputeDeviceKind(StrEnum):
    """
    What kind of device this is.

    A named schema rather than an inline enum because an inline one
    generated a bare `Kind` class, which is too generic to sit in a
    module every component imports.

    Note `cpu` is a member, which is why the surrounding schema is
    `ComputeDevice` and not `Accelerator`: a list that includes CPUs
    is a device list. The narrower `HostAccelerator.accelerator` on
    the agent keeps its own name and its own values — it answers
    "which prebuilt engine build fits this machine", not "what can
    this host compute on".

    """

    cuda = 'cuda'
    rocm = 'rocm'
    xpu = 'xpu'
    metal = 'metal'
    cpu = 'cpu'


class EngineKind(StrEnum):
    """
    Which engine adapter constructs the argv and interprets
    readiness. Deliberately a closed enum rather than a free string:
    an engine is supported exactly when an adapter exists for it,
    and without an adapter there is nothing that knows how to start
    it or tell when it is ready.

    `kev` drives upstream `python -m kev.serve` and loads Kev
    decision checkpoints (`kev_checkpoint` format) — a decision
    model, not a chat model: its server speaks the System One
    protocol and its companion driver serves `POST /v1/decide`,
    never completions. Like vLLM it loads the model *before*
    binding its port (read off `kev/serve.py` at the pinned commit
    and observed live 2026-09-22), so alive-and-refusing is
    `loading`; unlike every other engine it handles one request at
    a time, which its driver advertises as a concurrency limit.
    Its bind is hardcoded to loopback upstream, which is the
    posture Eugene wants: the gateway is the authenticated front
    door.

    `llama_cpp` drives upstream `llama-server` and loads GGUF.
    `vllm` drives upstream `vllm serve` and loads safetensors.
    `mlx` drives upstream `mlx_lm.server` and loads MLX-format
    safetensors, on Apple silicon only — experimental until a
    physical Mac run is recorded. We never ship an engine — every
    one of them is an upstream project we wrap and track.

    They differ in far more than argv, and that is why readiness
    is per-adapter rather than one shared TCP check:
    `llama-server` answers `/health` while it loads and reports that
    it is loading, whereas vLLM binds its port *before* loading the
    model and refuses connections until the model is in memory — so
    for minutes it is indistinguishable, over the network alone,
    from a process that died. `mlx_lm.server` is a third mechanism
    again and the most awkward: it serves HTTP immediately, and at
    the pinned release its `/health` answers a hardcoded
    `{"status": "ok"}` while the model is still loading on another
    thread, so **no read-only probe can tell loading from ready**.
    Its adapter proves residency by asking for one token, once per
    process, and only then treats the health endpoint as evidence.
    (Upstream `main` has since taught `/health` to answer 503
    `unavailable` while loading; the adapter reads that as loading
    too, so a future pin gets the cheap probe for free.) They
    differ in acquisition too: a llama.cpp build is fetched and
    verified by us, while vLLM and mlx-lm are Python packages the
    operator installs themselves. See `EngineAcquisition.policy`.

    Lives here rather than on the agent because two components
    reference it: the agent's engines and runtimes, and a
    library `ModelProfile`, which names the engine its launch flags
    are written for.

    """

    llama_cpp = 'llama_cpp'
    vllm = 'vllm'
    mlx = 'mlx'
    kev = 'kev'


class ModelFormat(StrEnum):
    """
    On-disk format of a model. A dimension of the data model rather
    than an assumption (locked 2026-09-08), and the differences are
    load-bearing rather than cosmetic.

    * `gguf` — a single file, quantized, carrying its own metadata
      and tokenizer. Large models may be **split** into
      `…-00001-of-0000N.gguf` shards, of which only the first is
      named on a launch line. A multimodal GGUF ships its vision
      projector as a separate file in the same directory, which is
      not itself a model.
    * `safetensors` — a directory: `config.json` plus one or more
      weight files plus tokenizer files. Unquantized in practice,
      so **no quant tier** — a safetensors model is sized, not
      tiered, and the quant fields exist only on the GGUF side.
    * `kev_checkpoint` — a directory holding a rank-limited LoRA
      adapter (`adapter_config.json` + `adapter_model.safetensors`),
      a pointer/decision head (`head.pt`), tokenizer files and
      calibration/provenance artifacts (`provenance.json`), loaded
      by Kev's own loader on top of a separately downloaded base
      model named in the adapter config. Measured off the published
      `jaredpalmer/kev-0.8b` checkpoint on 2026-09-22. **Not an
      ordinary adapter**: a plain LoRA directory is skipped by the
      scanner on purpose, and the decision head is what makes this
      one a launchable model instead. Decision-only —
      `ModelCapabilities.decision`, never `chat`.

    Shared because it appears on both sides of a join: a library
    entry declares what a model *is*, and
    `EngineDescriptor.modelFormats` declares what an engine can
    *load*. Nothing can serve a safetensors model until the vLLM
    adapter lands, and that answer comes from the engine's
    descriptor rather than from anything the library knows.

    """

    gguf = 'gguf'
    safetensors = 'safetensors'
    kev_checkpoint = 'kev_checkpoint'


class RetryDisposition(StrEnum):
    """
    Safe means this attempt did not accept application work and may
    be replayed before any output. Terminal means the request must
    be corrected. Indeterminate means work may have occurred; do not
    replay automatically. Missing classification on a server failure
    is indeterminate, never implicit permission to retry.

    """

    safe = 'safe'
    terminal = 'terminal'
    indeterminate = 'indeterminate'


class Problem(BaseModel):
    """
    Error response shape, modeled on RFC 7807 (problem+json). Every
    Eugene Plexus component returns this for 4xx / 5xx responses.

    """

    type: str = Field(
        ...,
        description='A URI reference identifying the problem type, per RFC 7807.\nModeled as a plain string rather than `format: uri` to keep\nsentinel values like `about:blank` and ergonomic at call sites.\n',
    )
    title: str = Field(..., description='Short human-readable summary.')
    status: int = Field(..., description='HTTP status code.')
    detail: str | None = Field(
        None, description='Human-readable explanation specific to this occurrence.'
    )
    instance: str | None = Field(
        None,
        description='A URI reference identifying the specific occurrence. Modeled\nas a plain string for the same reason as `type`.\n',
    )
    component: str | None = Field(
        None,
        description='Eugene Plexus component name that originated the error\n(e.g. `"gateway"`, `"inference-driver:left"`).\n',
    )
    retryDisposition: RetryDisposition | None = Field(
        None,
        description='Safe means this attempt did not accept application work and may\nbe replayed before any output. Terminal means the request must\nbe corrected. Indeterminate means work may have occurred; do not\nreplay automatically. Missing classification on a server failure\nis indeterminate, never implicit permission to retry.\n',
    )
    retryAfterSeconds: float | None = Field(
        None,
        description='Parsed provider Retry-After delay; a scheduling hint, not permission to replay.',
        ge=0.0,
    )


class Status(StrEnum):
    ok = 'ok'
    degraded = 'degraded'
    error = 'error'


class Health(BaseModel):
    """
    Liveness / readiness response shape.
    """

    status: Status
    version: str | None = Field(None, description='Component version (semver).')
    component: str | None = Field(
        None, description='Component identifier (e.g. `"inference-driver"`).'
    )
    safeMode: bool | None = Field(
        False,
        description="True when the component was started with the agent's\nsafe-mode env var set\n(`EUGENE_PLEXUS_<KIND>_SAFE_MODE=1`) and is therefore\nrunning on built-in defaults instead of its persisted\nconfig. Components in safe mode are reachable for config\nediting (`PATCH /v1/config` writes to disk normally) but\nshould be considered non-functional for their primary\npurpose until restarted without the flag. `status` is\nalso reported as `degraded` while safe mode is in effect.\n",
    )
    details: dict[str, Any] | None = Field(
        None, description='Optional component-specific health detail.'
    )


class ConfigValueType(StrEnum):
    """
    The kind of value a config field holds. The UI uses this to pick
    a renderer (text input, dropdown, password field, etc.).

    Three of these hold more than a scalar. `path_list` is an
    ordered JSON array of directory paths on the component host —
    the library's model roots are the first and so far only user —
    and the UI renders it as an add/remove list of directory pickers
    rather than a text field, because asking someone to
    comma-separate Windows paths is asking for a bug report. Order
    is preserved and meaningful: it is the order the operator sees,
    and M3's downloader offers the first entry as the default
    destination.

    `url_list` is the same argument one type over: an ordered JSON
    array of URLs, rendered as an add/remove list of address fields.
    Added at M5 for the control root's standby endpoints, which are
    inherently plural — *"N standbys is a configuration, not a
    mechanism"* — and which have no natural single-value spelling.
    A comma-separated text field would be the same bug report
    `path_list` exists to avoid, and reusing `path_list` for
    addresses would tell every UI to open a directory picker.
    Validation is the field's business rather than the type's; what
    the type promises is a list whose entries are addresses.

    `runtime_name` holds the `name` of a supervised engine runtime,
    and UIs render it as a dropdown sourced from the agent's
    `GET /v1/runtimes`. It exists because `componentKindHint` cannot
    do this job: a runtime is deliberately not a component, so
    `/v1/components` does not list one. What is saved is the
    runtime's *name*, never its URL — the agent assigns the port
    when the operator does not pick one, so a stored URL would
    encode a number the operator never chose and does not own, and
    would be wrong the moment the runtime moved. Its first user is
    the inference-driver's `runtimeName`, which is how a driver
    follows the engine process it fronts.

    `node_name` holds the `name` of an enrolled node, rendered as a
    dropdown sourced from the control root's `GET /v1/nodes`. Same
    reasoning as `runtime_name` one level up: a node is not a
    component either, so `componentKindHint` cannot source it, and
    what is saved is the name rather than a URL because the address
    of a host is topology the control root owns.

    `model_slots` is the gateway's priority-list surface, and the
    one value here that holds objects. An ordered JSON array of
    `{"model": <alias a client asks for>, "targets": [<model id>,
    ...]}`: a request for `model` is served by the drivers serving
    `model` itself, then by the drivers serving each target in
    order, cascading on failure. Targets are **model ids, not driver
    names**, because a model id names a replica set — every driver
    currently serving it, load-balanced — and a driver name would
    name one process. That is why the value reserved since M2 as
    `driver_list` was renamed when M6 defined it: the old name said
    the wrong thing about what goes in the list. A cloud
    subscription is a target like any other, because a
    `claude_code_cli` driver already serves a model id. UIs without
    a structured renderer for it fall back to editing the JSON.

    `path_mappings` (M11) is an ordered JSON array of `PathMapping`
    — `{"from": <a directory as another machine states it>, "to":
    <the same directory on this host>}`. Its one user is the agent's
    `pathMappings`, which is how a node opens model files a library
    on another host described by *its* path: `/models` on the NAS
    is `Z:\\models` here. UIs render it as rows of two directory
    fields, the right-hand one browsable on the component's own
    host, and offer the library's configured roots as suggestions
    for the left. Matching, precedence and translation rules are on
    the agent's field description, not here — the type promises a
    list of pairs and nothing about what they mean.

    `library_folders` (2026-09-14) is an ordered JSON array of
    `LibraryFolder` — `{"path": <a directory on the library's
    host>, "mounts": [<where other machines find the same
    directory>, ...]}`. Its one user is the library's `modelRoots`,
    which was a `path_list` until the reach of a folder moved onto
    the folder: a folder is one exported share, mounted the same
    way on every node of one OS, so the library says where once and
    every node inherits it rather than each node carrying a row per
    folder. A bare string is accepted wherever a `LibraryFolder` is
    expected and means a folder with no mounts — so a config file,
    a PATCH body or a default written for `path_list` still works,
    and `GET /v1/config` always answers in the object form. UIs
    render it as rows of one browsable directory (the library's
    host) plus its mounts; the per-node grid over it is the
    Library's Folders page, not this field.

    `share_credentials` (R2.6, 2026-09-18) is an ordered JSON array
    of `ShareCredential` — `{"host": <a file server>, "username":
    ..., "password": ...}`. Its one user is the agent's
    `shareCredentials`, which is how a host that runs Eugene as a
    Windows **service** reaches an authenticated share at all: a
    service has none of the per-user credentials the person who
    installed it collected by hand. It is the only value here whose
    entries contain a secret, so it carries `secret`'s rule per
    entry rather than per field — the password is redacted in `GET`,
    accepted in `PATCH`, and an entry that omits it keeps the stored
    one. UIs render it as rows of host / user / password, with the
    password a password input, and must not display a redacted
    entry as though its password were empty.

    """

    string = 'string'
    integer = 'integer'
    number = 'number'
    boolean = 'boolean'
    enum = 'enum'
    secret = 'secret'
    file_path = 'file_path'
    path_list = 'path_list'
    url = 'url'
    url_list = 'url_list'
    duration = 'duration'
    runtime_name = 'runtime_name'
    node_name = 'node_name'
    model_slots = 'model_slots'
    path_mappings = 'path_mappings'
    library_folders = 'library_folders'
    share_credentials = 'share_credentials'


class ConfigFieldShowWhen(BaseModel):
    """
    Predicate over another `ConfigField`'s current value. The UI
    renders the field this is attached to only when the named field
    equals the given value (or matches one entry in the given list).

    """

    key: str = Field(
        ...,
        description='`key` of another field in the same `ConfigSchema` to compare\nagainst.\n',
    )
    equals: Any = Field(
        ...,
        description="Value the named field must equal for this field to render.\nUntyped — when scalar, matches by literal equality against\nthe referenced field's `valueType`. When an array, matches\nif the referenced field's current value equals any entry\n(set-membership). Use the array form for a field that\napplies to multiple entries of an enum (e.g. an `apiKey`\nfield shared across several OpenAI-compatible providers).\n",
    )


class ConfigDocument(BaseModel):
    """
    Current effective config values, keyed by `ConfigField.key`.
    Values of fields with `sensitive: true` are returned as the
    literal string `"<redacted>"` regardless of whether they are
    set. Returned by `GET /v1/config`.

    """

    model_config = ConfigDict(
        extra='allow',
    )


class ConfigUpdateRequest(BaseModel):
    """
    Partial update for `PATCH /v1/config`. Every present key is
    set; absent keys are left unchanged. To revert a field to its
    default, send `null` as the value. Sensitive fields are written
    through directly (the redacted form sent back by GET is never
    accepted as a write value).

    """

    model_config = ConfigDict(
        extra='allow',
    )


class ConfigFieldError(BaseModel):
    """
    A per-field validation failure during PATCH.
    """

    key: str
    message: str


class ConfigUpdateResult(BaseModel):
    """
    Outcome of a `PATCH /v1/config` call. Validation failures on
    individual keys do not abort the whole request — valid changes
    are applied, invalid ones are reported in `rejected`.

    """

    applied: list[str] = Field(
        ..., description='Keys that were validated and applied successfully.'
    )
    rejected: list[ConfigFieldError] = Field(
        ...,
        description='Keys whose new values failed validation. The current value\nis preserved.\n',
    )
    requiresRestart: bool = Field(
        ...,
        description='True if any key in `applied` has `requiresRestart: true`,\nmeaning a process restart is needed for the change to take\neffect. The UI should surface this to the user.\n',
    )
    pendingRestart: list[str] | None = Field(
        None,
        description='Keys whose new values are stored but not yet active. Subset\nof `applied`. Empty unless `requiresRestart` is true.\n',
    )


class ConfigTestRequest(BaseModel):
    """
    Optional override for `POST /v1/config/test`. Same shape as
    `ConfigUpdateRequest`: keys override the saved config for the
    duration of the test only. Useful for "Test Connection" UIs where
    the operator wants to verify a new API key, URL, or model
    identifier before committing it. Send an empty body (`{}`) to
    test the saved config as-is.

    """

    overrides: ConfigUpdateRequest | None = None


class ConfigTestResult(BaseModel):
    """
    Result of a `POST /v1/config/test` invocation. Components decide
    what "test" means for their own surface: an inference-driver runs
    a minimal `generate()` round-trip against its backend; the
    gateway probes every driver it can route to; the library checks
    that its configured model directories are readable.

    """

    ok: bool = Field(
        ..., description='True iff the test invocation succeeded end-to-end.'
    )
    component: str = Field(
        ...,
        description='Component identifier (matches `ConfigSchema.component`).\nEchoed for UI clarity when several /v1/config/test responses\nland in the same view.\n',
    )
    latencyMs: int = Field(
        ..., description='Wall-clock time the test took, in milliseconds.'
    )
    summary: str | None = Field(
        None,
        description='One-line human-readable result summary. Always set when\n`ok` is true; may be set on failure to add context beyond\n`error`.\n',
    )
    sampleOutput: str | None = Field(
        None,
        description="Brief sample of the data the test produced — e.g. assistant\ntext from an inference-driver `generate()` round-trip. May be\ntruncated to keep the response small. Omitted when there's\nnothing useful to show.\n",
    )
    error: str | None = Field(
        None,
        description='Human-readable error message. Set when `ok` is false. Should\nbe specific enough that the operator can act on it (e.g.\n`"openaiApiKey rejected: 401 Unauthorized"`).\n',
    )


class SecurityMode(StrEnum):
    """
    How a host retains access to its master encryption key between
    restarts. The component's config schema lists the supported
    subset: the agent offers the first two modes; the control root
    also offers `passphrase_file`.

    * `prompt_on_startup` — passphrase required at every agent
      start. Master key lives only in process memory. Best for
      shared environments, sensitive conversations, security-
      conscious operators. A power outage means Eugene stays
      offline until the operator re-enters the passphrase.
    * `os_keyring` — master key stored in the OS secret store
      (Windows Credential Manager / macOS Keychain / Linux Secret
      Service via the `keyring` Python lib). OS unlocks tied to
      user login; Eugene auto-recovers from restarts. Best for
      home / personal-use installs and anyone who wants minimum
      friction. Anyone with the OS account can also start Eugene.
    * `passphrase_file` — the control root reads a mounted passphrase
      at startup from `EUGENE_PLEXUS_CONTROL_PASSPHRASE_FILE`. For
      containers and other hosts without a keyring. An absent or
      unreadable file leaves the root sealed, with a diagnosis in
      its log. Access to that file permits unlocking the root.

    """

    prompt_on_startup = 'prompt_on_startup'
    os_keyring = 'os_keyring'
    passphrase_file = 'passphrase_file'


class AuthLoginRequest(BaseModel):
    """
    Login request body sent by the UI to `POST /v1/auth/login` on
    the agent. The passphrase is the same one the operator set
    in the wizard. The agent verifies its Argon2id hash; on match,
    issues a session token.

    """

    passphrase: str = Field(..., min_length=1)


class AuthLoginResponse(BaseModel):
    """
    Issued on successful login. The UI stores `sessionToken` as a
    Secure / HttpOnly / SameSite=Strict cookie or in memory; every
    subsequent proxy request includes it as
    `Authorization: Bearer <token>`.

    """

    sessionToken: str = Field(
        ...,
        description='Opaque bearer token. Signed and validated server-side; the\nUI should never inspect its contents. Lifetime is bounded\nby `expiresAt`. New installs and key rotations use JWT\n`alg: EdDSA` with Ed25519. Existing HS256 installs retain\ntheir 32-byte key until explicit rotation. Agent and control\nhold private signing keys; gateway, library and driver hold\npublic verification keys after migration. Verifiers select\nexactly one algorithm from trusted key material, not from\ntoken headers. Rotation invalidates all prior tokens;\nthere is no simultaneous HS256/EdDSA acceptance window.\n',
    )
    expiresAt: AwareDatetime
    operatorName: str | None = Field(
        None,
        description='The operator\'s display name from the constitution\n(typically "operator" or whatever the operator set).\nEchoed for UI welcome strings.\n',
    )


class Alg(StrEnum):
    """
    Encryption algorithm identifier.
    """

    secretbox_xsalsa20poly1305 = 'secretbox-xsalsa20poly1305'


class MasterKeyEnvelope(BaseModel):
    """
    Encrypted-at-rest envelope for sensitive config fields. The
    on-disk YAML for fields marked `sensitive: true` is stored as
    this envelope when v0.2 security is enabled; the component
    decrypts using the master key passed in by the agent at
    spawn time (env var `EUGENE_PLEXUS_<KIND>_MASTER_KEY`,
    base64-encoded).

    Algorithm: libsodium secretbox (XSalsa20-Poly1305). The nonce
    is generated per-encryption and stored alongside the
    ciphertext. The master key is 32 bytes derived from the
    operator's passphrase via Argon2id with parameters chosen at
    first-run time and persisted in the agent's state.

    Components MAY accept plaintext values in PATCH requests
    (current behavior); on persist, they encrypt to this envelope
    if the master key is available. GET requests continue to
    return `"<redacted>"` for sensitive fields regardless of
    envelope-vs-plaintext on disk.

    """

    alg: Alg = Field(..., description='Encryption algorithm identifier.')
    nonce: str = Field(
        ...,
        description='Base64-encoded 24-byte nonce. Generated per-encryption,\nnever reused with the same key.\n',
    )
    ciphertext: str = Field(..., description='Base64-encoded ciphertext + auth tag.')


class RestartResult(BaseModel):
    """
    Acknowledgement returned by `POST /v1/admin/restart`. The
    component schedules its own process exit shortly after returning
    this response (typically a few hundred ms — long enough for the
    HTTP response to flush). The component does NOT bring itself
    back up; a process supervisor (systemd, docker-compose, the
    deploy launcher, etc.) is expected to relaunch it. In v0.1
    personal-use deploys without a supervisor, the operator
    relaunches manually.

    """

    scheduled: bool = Field(
        ...,
        description='True if the component accepted the restart and an exit is\nqueued. Always true in v0.1 — the endpoint has no reason to\nrefuse — but typed as a boolean so future versions can gate\non (e.g.) an in-flight long-running operation.\n',
    )
    delayMs: int = Field(
        ...,
        description='How long the component intends to wait before calling exit,\nmeasured from the moment the response is sent. Lets clients\ntime their UI ("restarting in 0.5s…") and decide when to\nstart polling `/healthz` for the relaunched process.\n',
        ge=0,
    )
    message: str | None = Field(
        None,
        description='Optional human-readable note (e.g. "logs flushed, exiting\nnow"). UI may display this in the restart-progress dialog.\n',
    )


class ShareCredential(BaseModel):
    """
    A user name and password this host uses to reach one file server.

    **The unit is the server, not the share**, and that is a Windows
    constraint rather than a simplification: Windows refuses a second
    set of credentials to a server it already holds a session with
    (`ERROR_SESSION_CREDENTIAL_CONFLICT`, 1219), so a per-share
    credential would be a field that cannot always be honoured. One
    entry covers every share on that host.

    **Why this exists at all.** An agent that runs as a Windows
    service has no per-user credential store, so the entry a person
    once typed into Explorer is invisible to it — and at Windows 11
    defaults there is no guest fallback either
    (`EnableInsecureGuestLogons` is 0), so a share that asks for
    nobody in particular is still refused with
    *"your organization's security policies block unauthenticated
    guest access"* (measured 2026-09-18 against the live install's
    own NAS). Without this the agent comes back after a reboot
    unable to read a single model, with every health check green.

    **Per node, and that is `library-folders-and-reach`'s shape
    rather than a departure from it.** A folder states its `mounts`
    once because a mount is a property of the share; a credential is
    a property of *this machine's relationship to* the share, which
    is exactly what `pathMappings` already is. Nodes do not inherit
    credentials, and a folder never carries one.

    Nothing here is required to mount anything: the agent asks the
    OS to establish the session, and an operator who has already
    arranged access another way leaves the list empty.

    """

    host: str = Field(
        ...,
        description="The file server, as the paths that need it spell it — a host\nname or an address, with no leading slashes and no share\nname. `192.168.16.252` covers `\\\\192.168.16.252\\downloads`\nand `\\\\192.168.16.252\\appdata` both. Matched\ncase-insensitively, because a server name is.\n\nA name and an address for the same machine are **two\ndifferent servers** to Windows, which keys a session by the\nname it was dialled with. That is a tripwire worth knowing\nrather than a rule to work around: spell it here the way the\nLibrary folder's mounts spell it.\n",
    )
    username: str = Field(
        ...,
        description='The account on the file server, not on this machine.\n`DOMAIN\\user` where the server wants one.\n',
    )
    password: str | None = Field(
        None,
        description="Redacted in `GET /v1/config` exactly as a `secret` scalar is\n— the value comes back as null and the entry keeps its `host`\nand `username`, so a UI can render the row without ever\nholding the secret. A `PATCH` that omits `password` on an\nentry whose `host` already exists **keeps the stored one**,\nso editing a user name does not silently blank the password;\nan explicit empty string clears it.\n\n**At rest it is sealed with the install's master key**, the\nsame envelope a driver's `apiKey` gets, so it is not\nreadable from the config file — and so it is readable only\nonce the agent is unlocked. On a host whose `securityMode`\nis `prompt_on_startup` that means shares are not reachable\nuntil somebody signs in, which is the same thing everything\nelse behind the master key already does and is reported the\nsame way rather than failing as a missing file.\n",
    )


class PathMapping(BaseModel):
    """
    One rule for reading a path that another machine wrote.

    The library describes each model by its path **on the library's
    own host**, and a runtime declaration copies that string
    verbatim — so when the engine runs elsewhere, the agent there is
    handed a path from a filesystem it does not have. A mapping says
    where the same directory is on this host: the NAS's `/models`
    is `Z:\\models` on the Windows box that mounts it. Nothing is
    copied or cached; the operator mounts the share, and this tells
    the agent where they mounted it.

    Shared here because it appears in two places on the agent: as
    the entries of the `pathMappings` config field, and as
    `ModelLocation.mapping` on an admission answer, which reports
    the rule that applied. Two definitions of one pair would drift.

    """

    from_: str = Field(
        ...,
        alias='from',
        description="A directory as the other machine states it — in practice a\nlibrary root, spelled exactly as the library's own\n`GET /v1/config` lists it. Its shape decides how it matches:\na drive letter or UNC prefix means Windows rules (case-\ninsensitive, `/` and `\\` interchangeable); a leading `/`\nmeans POSIX rules. The agent cannot know the library's\noperating system, and the string came from it, so the\nstring stands in.\n",
    )
    to: str = Field(
        ...,
        description="The same directory on the host holding this config. Used\nverbatim, `~` expanded; the remainder of a matched path is\nre-joined onto it with this host's own separator.\n",
    )


class LibraryFolder(BaseModel):
    """
    One directory the library catalogues, and where other machines
    find it (2026-09-14).

    `path` is the directory as the library's own host spells it —
    what the scanner walks, what a `ModelSummary.path` starts with,
    the left-hand side of every rule that reaches it. `mounts` is
    the same directory as **other** machines see it: a POSIX-shaped
    entry is for Linux and macOS nodes, a Windows-shaped one (drive
    letter or UNC) for Windows nodes, and a node takes the first
    entry of its own shape. That is the whole of "how does node X
    reach folder Y" for every node that mounts the share where the
    folder says; a node that mounts it elsewhere carries one
    override in its agent's `pathMappings`, and a node with no
    mount of its shape opens `path` as written — the identical-mount
    convention, and every single-host install.

    The rule this replaces was per node per folder, on each node's
    agent, and grew as nodes × folders with every row typed by hand.
    This is per folder, stated once. Nothing is copied or cached:
    the operator mounts the share, this says where.

    """

    path: str = Field(
        ...,
        description="Absolute, as the library's host spells it. Immutable in the\nsense that changing it is a different folder: models are\nidentified by their path under it.\n",
    )
    mounts: list[str] | None = Field(
        [],
        description='Absolute paths, each Windows- or POSIX-shaped; the shape\nsays which nodes it is for. Order matters only among entries\nof one shape, where the first wins. Empty means "reached at\n`path`, or not at all".\n',
    )


class DirectoryEntryKind(StrEnum):
    """
    Files appear only when a listing asked for `includeFiles`. A
    directory picker never does; a `file_path` field's picker would,
    which is why the flag exists on the endpoint without a UI yet.

    """

    directory = 'directory'
    file = 'file'


class FinishReason(StrEnum):
    """
    **`content_filter` is separate from `error` since
    2026-09-19**, and the two were one value for the same
    reason `tool_calls` was folded into `stop` before step 6:
    the map had a row for a state nobody had a use for yet, so
    the state was reported as its nearest neighbour.

    A filtered answer is not a backend error — nothing broke,
    the backend did exactly what it was configured to do — and
    it is not a natural end either, which is what the caller
    saw. `error` means the generation was truncated because
    something failed mid-stream; `content_filter` means a
    classifier stopped it on purpose. OpenAI and Anthropic each
    have their own name for this state and the gateway renders
    it in the caller's vocabulary, so a client that switches on
    the field gets the vendor value it already understands.

    """

    stop = 'stop'
    length = 'length'
    stop_sequence = 'stop_sequence'
    tool_calls = 'tool_calls'
    content_filter = 'content_filter'
    error = 'error'


class FunctionDefinition(BaseModel):
    name: str
    description: str | None = None
    parameters: dict[str, Any] | None = Field(
        None, description='A JSON Schema object, passed through verbatim.'
    )
    strict: bool | None = None


class Function(BaseModel):
    name: str


class NamedToolChoice(BaseModel):
    type: Literal['function']
    function: Function


class FunctionCall(BaseModel):
    name: str
    arguments: str = Field(
        ...,
        description='Arguments as a JSON **string**, not an object — a model can\nemit invalid JSON and the string preserves what it actually\nsaid. Not parsed here.\n',
    )


class Function1(BaseModel):
    name: str | None = None
    arguments: str | None = None


class ToolCallDelta(BaseModel):
    index: int
    id: str | None = None
    type: Literal['function'] = 'function'
    function: Function1 | None = None


class Type(StrEnum):
    text = 'text'
    json_object = 'json_object'
    json_schema = 'json_schema'


class ResponseJsonSchema(BaseModel):
    name: str
    description: str | None = None
    schema_: dict[str, Any] = Field(..., alias='schema')
    strict: bool | None = None


class Usage(BaseModel):
    """
    Token accounting. Some backends (CLI subprocess) may report nulls.
    """

    promptTokens: int | None = Field(None, ge=0)
    completionTokens: int | None = Field(None, ge=0)
    totalTokens: int | None = Field(None, ge=0)


class EmbedRequest(BaseModel):
    """
    Text to embed. Batched because every backend that does this
    accepts a batch, and a per-item round trip would multiply the
    control plane's own overhead by the size of a document set.

    """

    localOnly: bool | None = Field(
        False,
        description='Internal policy; require a local active engine before forwarding any input.',
    )
    input: list[str] = Field(
        ...,
        description='One entry per vector to produce. Order is preserved: the\nn-th vector in the response is the n-th input, which is the\nonly thing that lets a caller match them up, since an\nembedding carries no identity of its own.\n',
        min_length=1,
    )
    requestId: str | None = Field(
        None,
        description='Correlation id, echoed back. Same role as on `GenerateRequest`.',
    )


class EmbedResponse(BaseModel):
    embeddings: list[list[float]] = Field(
        ...,
        description='One vector per input, in the order the inputs arrived.\nFloats, always — see the operation description for why this\nsurface does not carry base64.\n',
    )
    modelId: str | None = Field(
        None,
        description="The model that produced these vectors, as the **public**\nidentifier — normalized the same way `GenerateResponse`'s\nis when `upstreamModelId` is in play. **Load-bearing beyond\nattribution:** vectors from two models are not comparable,\nso a caller storing them needs to know which model's space\nthey belong to — and the public id is the only name that\nstays stable across replicas of one model on several nodes.\n",
    )
    backend: BackendKind | None = None
    usage: Usage | None = None
    latencyMs: int | None = Field(None, ge=0)
    requestId: str | None = None


class Type1(StrEnum):
    noul = 'noul'
    choice = 'choice'
    score = 'score'


class DecisionQuestion(BaseModel):
    """
    One typed question, in the pinned System One vocabulary. The
    shape of `criteria` depends on `type` and is validated in code
    against the pinned protocol: for `noul` an optional object
    mapping `"true"` and `"false"` to outcome descriptions; for
    `choice` a required map of 1-255 option names to rubric text or
    null; for `score` a required array of 2-10 ordered level
    descriptions, lowest first. **Fields beyond these are refused,
    never dropped** — a knob the protocol does not define, silently
    removed, would answer a different question than the caller
    asked.

    """

    type: Type1
    instructions: str | dict[str, Any] | list[Any] = Field(
        ...,
        description='What to decide — a string, or structured content the\nprovider accepts.\n',
    )
    criteria: Any | None = Field(
        None, description='Shape depends on `type`; see above.'
    )


class DecisionAnswer(BaseModel):
    """
    One validated answer. `type` echoes the question's kind and
    exactly the matching fields are present — the driver has already
    refused a backend that answered otherwise, so a caller can
    switch on `type` without defending against a half-shaped answer.

    """

    type: Type1
    noul: float | None = Field(
        None,
        description='`noul` only: the probability the answer is yes.',
        ge=0.0,
        le=1.0,
    )
    choice: str | None = Field(
        None, description='`choice` only: the highest-probability option name.'
    )
    score: float | None = Field(
        None,
        description='`score` only: the probability-weighted value across the\nordered levels, 0-indexed against `legend`.\n',
    )
    legend: dict[str, str] | None = Field(
        None, description='`score` only: level indices to their descriptions.'
    )
    probabilities: dict[str, float] | None = Field(
        None,
        description='`choice` and `score`: the full distribution, validated to be\nover the legal options/levels with finite values.\n',
    )
    confidence: float | None = Field(
        None,
        description="`choice` and `score`: the provider's certainty, preserved as\nreported. Provider-specific calibration — never comparable\nacross models, and never manufactured by the driver when the\nprovider omits it.\n",
        ge=0.0,
        le=1.0,
    )


class DecisionResponse(BaseModel):
    answers: dict[str, DecisionAnswer] = Field(
        ..., description='One validated answer per request question, same keys.'
    )
    modelId: str | None = Field(
        None,
        description="The public model identifier, normalized exactly as\n`GenerateResponse.modelId` is — a backend's own name for\nitself is never echoed by a translating driver.\n",
    )
    reportedModel: str | None = Field(
        None,
        description="What the backend said served this request, verbatim —\nprovenance for calibration (`jev-1.13.0`, a Kev checkpoint\nid), preserved without becoming anyone's routing key.\n",
    )
    backend: BackendKind | None = None
    usage: Usage | None = None
    latencyMs: int | None = Field(None, ge=0)
    requestId: str | None = None


class Kind(StrEnum):
    noul = 'noul'
    choice = 'choice'
    score = 'score'


class DecisionCapability(BaseModel):
    """
    Present on `/v1/info` iff this driver serves `POST /v1/decide`.
    Its absence is how the gateway knows not to route decisions
    here; `chatCapable: false` beside it is how a decision-only
    backend refuses chat with a reason.

    """

    kinds: list[Kind] = Field(..., description='Question kinds the backend supports.')
    maxQuestions: int | None = Field(
        None, description='Per-request question ceiling. Absent means unknown.', ge=1
    )
    maxOptions: int | None = Field(
        None,
        description="Choice option ceiling. The protocol's own ceiling is 255;\na backend may be lower.\n",
        ge=1,
    )
    maxConcurrent: int | None = Field(
        None,
        description="How many requests the backend can hold at once. **Kev's\nserver handles exactly one** (a lock, no cross-caller\nbatching — read off `kev/serve.py` at the pinned commit), so\nits driver reports 1 and the layers above must not\nover-admit: a non-cancellable engine that is over-admitted\nholds capacity nobody can free.\n",
        ge=1,
    )


class Locality(StrEnum):
    """
    Active engine's configured trust classification. Managed local
    runtimes are local; cloud APIs and subscription CLIs are external.
    Custom HTTP endpoints require an explicit operator assertion;
    URLs, hostnames and loopback addresses never prove locality.
    Unknown and absent are ineligible for local-only routing.

    """

    local = 'local'
    external = 'external'
    unknown = 'unknown'


class Capabilities(BaseModel):
    """
    Backend capabilities the gateway keys off when routing.
    """

    supportedSettings: list[str] | None = Field(
        None,
        description='Explicit callerSettings this active adapter can carry without\ndropping them. This does not promise the provider accepts every\npossible value. Absent means unknown; ineligible for requests\nrequiring explicit settings. The driver still validates before\nexecution, including after a configuration change.\n',
    )
    streaming: bool | None = Field(
        None, description='Whether `/v1/generate/stream` emits true incremental tokens.'
    )
    imageInput: bool | None = Field(
        None,
        description='Whether the loaded model is confirmed to accept inline PNG/JPEG\nimages. Unknown or unverified backends report false. Rechecked\nbefore image generation; never inferred from the provider name.\n',
    )
    toolCalling: bool | None = Field(
        None,
        description='Whether this driver can carry `tools` to its backend and\nreport `toolCalls` back.\n\nThe gateway reads it to answer a question a harness\ncannot otherwise ask: a plain answer where a tool call\nwas expected looks identical whether the model declined\nor the backend never saw the tools. A driver that says\n`false` here is failed at the front door with a reason\ninstead.\n',
    )
    embeddings: bool | None = Field(
        None,
        description='Whether this driver can serve `POST /v1/embed`.\n\n**A property of the running backend, not of the model**,\nand not readable from anything: `llama-server`\'s\n`/props` carries no pooling or embedding field, and an\nOllama runner started for chat refuses with "This server\ndoes not support embeddings". So it is determined by\ntrying once and cached for the driver\'s lifetime — which\nis the right lifetime, since it cannot change without\nthe backend restarting.\n\nThe gateway reads it to mark which surface each model\nserves on `GET /v1/models`, and to refuse a chat request\nagainst an embeddings-only model with a reason instead\nof passing it down to fail obscurely.\n',
    )
    maxContextTokens: int | None = Field(
        None,
        description="The context window the backend **resolved**, read back\nfrom the backend itself — not the model's trained\nmaximum, and never an estimate.\n\nNull means unknown, and unknown is a real answer: a\nhosted provider exposes nothing to read, and a CLI\nsubscription has no window of its own to report. The\ngateway's `_smallest_context` folds this together with\nthe window a supervised runtime reports and publishes\nthe smallest as `x_eugene_plexus.context_length` on\n`GET /v1/models`, so a harness can size a prompt\nagainst the number that will actually apply.\n\n**Populated by a probe of the backend, which is why it\nexists at all.** A supervised runtime already tells the\nagent its window; this field is for the backend nobody\nsupervises — an Ollama or an LM Studio the operator\npoints us at — which until now reported no window\nanywhere. Contracted since M0 and populated by nothing\nuntil then, exactly as `streaming` was until M10.\n\n**Advertising, not enforcement.** Nothing here counts a\nprompt: the window is published so a caller can respect\nit, and a caller that does not is refused by the engine\nitself, whose count is exact. A backend that truncates\nsilently instead of refusing is caught after the fact —\nsee `x_eugene_plexus.prompt_truncated` in\n`gateway.yaml`.\n",
        ge=0,
    )
    chatCapable: bool | None = Field(
        True,
        description='Whether this driver serves `POST /v1/generate` at all.\nTrue for every backend that existed before decisions —\nabsent means chat-capable, so no existing driver changes\nmeaning — and **false for a System One backend**, whose\nonly surface is `POST /v1/decide`. The gateway reads it\nto refuse a chat request against a decision-only model\nwith a sentence naming `/v1/systemone`, instead of\nletting the request die as a protocol error inside a\nbackend that never spoke chat.\n',
    )
    decision: DecisionCapability | None = None


class DriverInfo(BaseModel):
    """
    Driver self-description, and the gateway's only source of truth
    for what this backend serves. A driver does not know its position
    in any topology: its operator-supplied name lives in the agent
    topology, not here.

    """

    locality: Locality | None = Field(
        'unknown',
        description="Active engine's configured trust classification. Managed local\nruntimes are local; cloud APIs and subscription CLIs are external.\nCustom HTTP endpoints require an explicit operator assertion;\nURLs, hostnames and loopback addresses never prove locality.\nUnknown and absent are ineligible for local-only routing.\n",
    )
    localOnlyEnforced: bool | None = Field(
        False,
        description='True only when this driver enforces GenerateRequest/EmbedRequest\nlocalOnly against the active engine before invoking it. A local\nclassification alone is insufficient for a protected request.\n',
    )
    backend: BackendKind
    provider: str | None = Field(
        None,
        description='Operator-friendly provider key from the driver\'s\nregistry (e.g. `"openai"`, `"xai"`, `"openrouter"`,\n`"claude_subscription"`). Reflects which subscription /\nservice this driver is wrapping — `backend` reflects the\n*protocol* underneath, which can be shared across many\nproviders (e.g. xAI, OpenRouter, Ollama all report\n`backend: openai_compat_http`). Optional; omitted when\nthe driver is in degraded mode and never finished\nconstructing.\n',
    )
    modelId: str | None = Field(
        None,
        description='The **public** model identifier — what the gateway routes\non and what callers name (e.g. `"claude-opus-4-7"`).\nOptional — omitted when the driver is configured to use the\nadapter\'s built-in default rather than pinning a specific\nmodel. When `upstreamModelId` is unset this is also what\nthe backend is asked for, which is every install that\npredates the split.\n',
    )
    upstreamModelId: str | None = Field(
        None,
        description="What this driver actually sends to its backend, when that\ndiffers from the public `modelId`. Exists because some\nbackends' served name is not ours to choose:\n`mlx_lm.server` answers only to upstream's `default_model`\nsentinel or to the model's absolute path — the first\ncollides across every MLX runtime in an install and the\nsecond publishes the operator's directory layout — so the\nsupervised runtime's companion driver advertises the public\nalias here as `modelId` and translates to the sentinel at\nthe backend boundary, nowhere else.\n\nDiagnostic, never a routing key: the gateway routes and\nauthorizes on `modelId` alone, and this value must not\nappear in any public model list. Defaults to `modelId` when\nunset. Responses report the public id (`GenerateResponse`\nand `EmbedResponse` `modelId`), so two runtimes serving\ndifferent models behind one upstream sentinel stay\ndistinguishable everywhere a caller looks.\n",
    )
    runtime: str | None = Field(
        None,
        description="The supervised engine runtime this driver is following, when\nit was configured with `runtimeName` rather than a literal\n`baseUrl`. Absent for a cloud provider, a CLI subscription,\nor any backend that is not a runtime this install\nsupervises.\n\nReported here despite the rule that a driver never says\nwhere it sits, because this is not the driver's own address —\nit is *what it serves*, which is exactly what `/v1/info` is\nfor. It lets the gateway and the UI show which engine\nprocess is behind a driver, so a model that is loaded but\nunroutable is diagnosable from the routing table instead of\nby reading two components' configs side by side.\n",
    )
    capabilities: Capabilities | None = Field(
        None, description='Backend capabilities the gateway keys off when routing.'
    )
    version: str | None = Field(None, description='inference-driver semver.')


class ComputeDevice(BaseModel):
    """
    One compute device on one host, as that host's agent detected it.

    Shared because it appears on both sides of a join: an agent
    reports its own devices on `GET /v1/node`, and the control root
    aggregates them into `Node.devices` — the cross-host
    inventory M3 deferred with the note that *"building a real
    inventory is topology work"*. Two copies of this shape would be
    two definitions of one fact, and the copy would be the one that
    went stale.

    Deliberately **not** the same thing as the agent's
    `HostAccelerator`, which answers a narrower question — "which
    prebuilt engine build should we fetch for this machine" — and
    describes a host in the singular. This is a device *list*,
    because a host with two cards is the case that makes replicas of
    one model possible.

    """

    kind: ComputeDeviceKind
    name: str | None = Field(
        None,
        description='Device name as the vendor reports it, e.g. `NVIDIA GeForce RTX 5090`.',
    )
    index: int | None = Field(
        None,
        description="Device ordinal on its own host — what `CUDA_VISIBLE_DEVICES`\nor `HIP_VISIBLE_DEVICES` in a runtime's `env` selects to pin\nthat runtime to one card.\n",
        ge=0,
    )
    memoryTotalBytes: int | None = None
    memoryFreeBytes: int | None = Field(
        None,
        description='Free decides whether a model fits, not total — M3 measured\n2.9 GiB of a 32 GiB card already held on an idle desktop.\nBoth are reported so the difference is visible rather than\nsurprising.\n',
    )


class ConfigField(BaseModel):
    """
    UI-renderable description of a single editable config field.

    """

    key: str = Field(
        ...,
        description='Stable machine-readable id, dot-separated for grouping\n(e.g. `"adapter.modelId"`).\n',
    )
    label: str = Field(..., description='Human-readable label for the UI.')
    description: str | None = Field(
        None, description='One-sentence explanation suitable for non-programmers.'
    )
    category: str = Field(
        ...,
        description='Group key for UI tabbing or sectioning (e.g. `"adapter"`,\n`"logging"`, `"network"`). Mapped to a display label via\n`ConfigSchema.categories`.\n',
    )
    valueType: ConfigValueType
    default: Any | None = Field(
        None,
        description='Default value if unset. Type matches `valueType`. Omitted\nfor fields with no default.\n',
    )
    enumValues: list[str] | None = Field(
        None, description='Allowed values when `valueType == enum`.'
    )
    suggestions: list[str] | None = Field(
        None,
        description="Discovery-time hints — values the operator might want\nbut which AREN'T enforced by validation. UIs render\nstring-typed fields with non-empty `suggestions` as a\ncombobox (free-text input with a dropdown of suggestions)\nrather than a strict dropdown. Use when the set of\nvalid values is large, partially-discoverable, or\nextends beyond what the component knows at the moment\n(e.g. local LLM model lists that update when the operator\npulls a new model). Distinct from `enumValues`:\nsuggestions are advisory, enumValues are mandatory.\n",
    )
    componentKindHint: ComponentKind | None = Field(
        None,
        description="Declarative rendering hint: this field references a peer\ncomponent of the given kind. UIs render any kind-hinted\nfield as a dropdown sourced from the agent's\n`/v1/components` (filtered by kind), with `(off)` as the\nfirst option (saves an empty string). For single-instance\nkinds (memory, identity, etc.) the dropdown UX collapses\nto effectively a toggle; for multi-instance kinds\n(inference-driver) the operator picks one. Pairs with a\nstring/url `valueType` — the saved value is still the\npeer's URL, the hint only changes how the UI looks it up.\nAvoids the OpenClaw trap of duplicating topology into\nfree-text URL fields the operator has to type by hand.\n",
    )
    enumLabels: list[str] | None = Field(
        None,
        description='Optional human-readable display labels paired one-to-one\nwith `enumValues`. UIs that render an enum as a dropdown\nshould show `enumLabels[i]` while still submitting\n`enumValues[i]` as the saved value. When omitted (or\nshorter than `enumValues`), UIs fall back to the raw\nvalue as the label. Useful where the stored key is\nmachine-friendly but the user-facing label isn\'t —\ne.g. `claude_subscription` saved, "Claude (Pro/Max)"\nshown.\n',
    )
    sensitive: bool | None = Field(
        False,
        description='If true, the value is redacted (`"<redacted>"`) in\n`ConfigDocument` responses but is accepted in\n`ConfigUpdateRequest`. Use for API keys, passwords, etc.\n',
    )
    required: bool | None = Field(
        False,
        description='If true, the component will refuse to start without this\nfield set (either in config or via env var fallback).\n',
    )
    minimum: float | None = Field(
        None, description='Validation hint for `integer` / `number` fields.'
    )
    maximum: float | None = Field(
        None, description='Validation hint for `integer` / `number` fields.'
    )
    pattern: str | None = Field(
        None, description='Regex validation hint for `string` / `url` / `file_path`.'
    )
    requiresRestart: bool | None = Field(
        False,
        description='If true, changes to this field via PATCH are accepted and\nstored but do not take effect until the component process\nrestarts. The UI should warn before submitting.\n',
    )
    showWhen: ConfigFieldShowWhen | None = Field(
        None,
        description="Conditional-rendering hint. When set, the UI should only\nrender this field when another field's current value matches\nthe condition. Used to hide adapter-specific fields\n(e.g. `openaiApiKey`) when a different adapter is selected.\nThe component still validates and stores the field\nregardless of UI visibility.\n",
    )


class ConfigSchema(BaseModel):
    """
    UI-renderable description of every editable config field this
    component accepts. Returned by `GET /v1/config/schema`. UIs use
    this to render a generic config editor without component-specific
    code.

    """

    component: str = Field(
        ..., description='Component identifier (e.g. `"inference-driver"`).'
    )
    fields: list[ConfigField]
    categories: dict[str, str] | None = Field(
        None,
        description='Map from category key (used in `ConfigField.category`) to\na human-readable section label. Optional; UIs may fall back\nto the raw key.\n',
    )


class DirectoryEntry(BaseModel):
    name: str
    path: str = Field(
        ..., description='Absolute path, ready to be used as a config value.'
    )
    kind: DirectoryEntryKind
    hidden: bool | None = Field(
        False,
        description='A dot-prefixed name, or the hidden attribute on Windows.\nOnly present in a listing that asked for `showHidden`.\n',
    )


class StreamToken(BaseModel):
    """
    One `event: token` payload. Exactly one of `text` or `toolCalls`
    is set.

    """

    text: str | None = Field(None, description="A fragment of the assistant's text.")
    toolCalls: list[ToolCallDelta] | None = Field(
        None,
        description='Fragments of one or more tool calls, accumulated by `index`.\n',
    )


class Tool(BaseModel):
    type: Literal['function']
    function: FunctionDefinition


class ToolCall(BaseModel):
    id: str
    type: Literal['function']
    function: FunctionCall


class ResponseFormat(BaseModel):
    type: Type
    json_schema: ResponseJsonSchema | None = None


class DecisionRequest(BaseModel):
    """
    One state, several named typed questions, answered together.
    Question names are the caller's own keys and come back verbatim
    on the response's `answers`. Question independence is the
    protocol's promise: each question is answered against the state
    alone, not against the other questions' answers.

    """

    state: str | dict[str, Any] | list[Any] = Field(
        ...,
        description='What is being judged — plain text, or structured data (an\nobject or array such as a ticket record or a chat log)\npassed through without re-serialization by the caller.\n',
    )
    questions: dict[str, DecisionQuestion] = Field(
        ..., description='Caller-named questions; at least one.'
    )
    localOnly: bool | None = Field(
        False,
        description='Internal policy; require a local active engine before\nforwarding any state, exactly as on `GenerateRequest`.\n',
    )
    requestId: str | None = Field(None, description='Correlation id, echoed back.')


class MessageContent1(RootModel[list[TextContentPart | ImageContentPart]]):
    root: list[TextContentPart | ImageContentPart] = Field(
        ...,
        description='Text, null for an assistant tool-call turn, or ordered user content parts.\nImages are inline PNG/JPEG only: four per request, 5 MiB decoded each,\n10 MiB decoded total, 16 million pixels each, maximum dimension 8192.\nJSON bodies are limited to 16 MiB. Remote URLs are never fetched.\n',
        min_length=1,
    )


class MessageContent(RootModel[str | MessageContent1 | None]):
    root: str | MessageContent1 | None = Field(
        ...,
        description='Text, null for an assistant tool-call turn, or ordered user content parts.\nImages are inline PNG/JPEG only: four per request, 5 MiB decoded each,\n10 MiB decoded total, 16 million pixels each, maximum dimension 8192.\nJSON bodies are limited to 16 MiB. Remote URLs are never fetched.\n',
    )


class DirectoryListing(BaseModel):
    """
    One directory on the component's own host, listed for a picker.

    Returned by `GET /v1/directories` on the library (whose host
    holds the model roots) and on the agent (whose host holds a
    path mapping's `to`, and any engine binary an operator points
    at). The same shape on both, because the UI has one picker and
    the only thing that differs is which machine's disk it is
    looking at — which is why `host` is on the response.

    This is the endpoint behind the promise `path_list` has carried
    since M2: *"an add/remove list of directory pickers"*. It lists
    what an operator could already type into a path field, on
    request, to the strongest credential there is; it is not a new
    capability and it is not a file browser.

    """

    host: str = Field(
        ...,
        description='The machine whose disk this is. On a multi-host install the\nanswer to "browse" is frequently a machine other than the\none the browser is on.\n',
    )
    path: str | None = Field(
        None,
        description='The directory listed, absolute and as this host spells it.\nAbsent when no `path` was asked for, in which case `entries`\nare the places to start from — every drive on Windows, `/`\non POSIX, and the home directory.\n',
    )
    parent: str | None = Field(
        None,
        description='The directory above `path`, so a picker can go up without\ndoing path arithmetic in a browser. Absent at a filesystem\nroot and when `path` is absent.\n',
    )
    entries: list[DirectoryEntry] = Field(
        ...,
        description='Sorted by name, directories first. Entries this component\nmay not read are omitted rather than failing the listing.\n',
    )


class GenerateResponse(BaseModel):
    content: str | None = Field(
        None,
        description='The generated assistant text. **Nullable since tool calling\nlanded:** a turn that only calls a tool produces no text,\nand an empty string would be a lie about what the model\nsaid. Was required; a response with `toolCalls` and no\n`content` is the common agent-loop case.\n',
    )
    toolCalls: list[ToolCall] | None = Field(
        None,
        description='Tools the model chose to call. Present when `finishReason`\nis `tool_calls`.\n',
    )
    finishReason: FinishReason = Field(
        ...,
        description="**`content_filter` is separate from `error` since\n2026-09-19**, and the two were one value for the same\nreason `tool_calls` was folded into `stop` before step 6:\nthe map had a row for a state nobody had a use for yet, so\nthe state was reported as its nearest neighbour.\n\nA filtered answer is not a backend error — nothing broke,\nthe backend did exactly what it was configured to do — and\nit is not a natural end either, which is what the caller\nsaw. `error` means the generation was truncated because\nsomething failed mid-stream; `content_filter` means a\nclassifier stopped it on purpose. OpenAI and Anthropic each\nhave their own name for this state and the gateway renders\nit in the caller's vocabulary, so a client that switches on\nthe field gets the vendor value it already understands.\n",
    )
    usage: Usage | None = None
    requestId: UUID | None = None
    backend: BackendKind | None = None
    modelId: str | None = Field(
        None,
        description='The public model identifier this driver serves (e.g.\n`"claude-opus-4-7"`) — the same value `/v1/info` advertises,\n**normalized**: when the driver translates to an\n`upstreamModelId` at the backend boundary, the backend\'s own\nname for itself is not echoed here. A caller that asked the\npublic alias gets the public alias back, on this field and\non the terminal frame of a stream alike.\n',
    )
    latencyMs: int | None = Field(
        None, description='End-to-end driver-side latency in milliseconds.'
    )


class Message(BaseModel):
    """
    A single message in a conversation. Deliberately close to the
    OpenAI / Anthropic chat message format so drivers don't have to
    re-shape on every hop.

    """

    role: Role
    content: str | MessageContent1 | None = Field(
        None,
        description='Text, null for an assistant tool-call turn, or ordered user content parts.\nImages are inline PNG/JPEG only: four per request, 5 MiB decoded each,\n10 MiB decoded total, 16 million pixels each, maximum dimension 8192.\nJSON bodies are limited to 16 MiB. Remote URLs are never fetched.\n',
    )
    toolCalls: list[dict[str, Any]] | None = Field(
        None,
        description="On an **assistant** message: the tool calls the model made,\nin OpenAI's `{id, type, function: {name, arguments}}` shape.\n\nDeliberately loose here. This is the *shared* schema, so a\ntightly-typed copy would be a third definition of the same\nobject alongside the gateway's and the driver's, and the one\nplace all three must agree is the wire format, which is\nOpenAI's and not ours to restate. The two API documents\ncarry the strict shapes.\n",
    )
    toolCallId: str | None = Field(
        None,
        description='On a **tool** message: which call this is the result of.\n`content` is the result, serialized by the caller.\n',
    )
    timestamp: AwareDatetime | None = Field(
        None, description='When the message was produced. Server-assigned if omitted.'
    )


class GenerateRequest(BaseModel):
    localOnly: bool | None = Field(
        False,
        description='Internal routing policy. When true the driver must refuse before\nforwarding any prompt/image unless its active engine is classified\nlocal. Never forward this field upstream. Checked on the active\nengine at execution, so stale gateway metadata cannot relax policy.\n',
    )
    callerSettings: list[str] | None = Field(
        None,
        description="A2 provenance: names of settings explicitly requested by the caller,\nusing this request's field names (maxTokens, temperature, topP, seed,\nstop, tools, toolChoice, responseFormat). The gateway preserves this\nlist on each fallback attempt. An adapter must refuse a known unsupported\nexplicit setting with 400, rather than silently dropping it. Settings\nsupplied only by profiles/defaults retain the adapter's default behavior.\nThis field is internal and is not forwarded to upstream providers.\n",
    )
    messages: list[Message] = Field(
        ...,
        description='Full prompt as an ordered conversation. Whatever system\nmessage the caller wants is already in here; the driver does\nnot modify, prepend to, or reorder it.\n',
    )
    maxTokens: int | None = Field(
        None,
        description="Maximum output tokens. Backend-clamped. Owned by the caller\n(the gateway) — the driver applies no local default. Adapters\nwhose backends don't expose this knob (agentic CLIs) refuse it when\ncallerSettings marks it explicit; inherited defaults remain ignored.\n",
        ge=1,
    )
    temperature: float | None = Field(
        None,
        description="Sampling temperature. Backend-clamped. Owned by the caller\n(the gateway, which resolves it from the model's settings\nprofile) — the driver applies no local default. Backends that\nreject the parameter outright, as some reasoning models do,\nrefuse explicit callerSettings and omit inherited defaults.\n",
        ge=0.0,
        le=2.0,
    )
    topP: float | None = Field(
        None,
        description='Nucleus sampling cutoff. Owned by the caller (the gateway)\nexactly as `temperature` is, and for the same reason: it\nchanges what the model says, so a driver never substitutes\none of its own.\n\n**Added 2026-09-19.** `gateway.yaml` had promised since M0\nthat `top_p` was passed through to backends that support it\nand dropped with a warning where they do not, and there was\nno field here to carry it — so the gateway accepted the\nvalue from its caller and silently discarded it, with no\nwarning logged anywhere. A knob that is read, validated and\nthrown away is worse than one that is refused.\n\nAn adapter whose backend has no such knob — the agentic\nCLIs — drops it and says so in its log, once per field, and\nanswers the request.\n',
        ge=0.0,
        le=1.0,
    )
    seed: int | None = Field(
        None,
        description='Deterministic-sampling seed. Owned by the caller, carried to\nbackends that implement it, dropped with a logged warning by\nadapters whose backends do not.\n\n**Added 2026-09-19 for the same reason as `topP`**, and it\nis the more load-bearing of the two: a caller asking for a\nseed is asking for a reproducible answer, and silently\ndropping it returns a different answer each time while the\ncontract says otherwise. Nothing in a response says whether\nthe seed arrived, so the failure is invisible to the caller\nby construction.\n',
    )
    stop: list[str] | None = Field(None, description='Optional stop sequences.')
    requestId: UUID | None = Field(
        None,
        description='Caller-supplied id for log correlation. Echoed in the response.',
    )
    tools: list[Tool] | None = Field(
        None,
        description="Tools the model may call, in OpenAI's shape. Carried down to\nthe backend unchanged and never executed here — the driver\nis a protocol adapter, and running a tool is the caller's\njob by the same reasoning that keeps output-affecting\nparameters on the gateway.\n\nAn adapter whose backend cannot carry tools MUST fail the\nrequest rather than drop the field. Dropping it yields a\nplain answer that a harness cannot distinguish from the\nmodel declining to call anything.\n",
    )
    toolChoice: ToolChoice | NamedToolChoice | None = Field(
        None,
        description='`none`, `auto`, `required`, or an object naming one\nfunction. Passed through.\n',
    )
    responseFormat: ResponseFormat | None = None
