# generated by datamodel-codegen:
#   filename:  inference-driver.yaml

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class ToolChoice(StrEnum):
    """
    `none`, `auto`, `required`, or an object naming one
    function. Passed through.

    """

    none = 'none'
    auto = 'auto'
    required = 'required'


class Role(StrEnum):
    """
    The speaker of a single message in a conversation. Matches the
    OpenAI / Anthropic chat roles so adapters never re-shape on a hop.

    """

    system = 'system'
    user = 'user'
    assistant = 'assistant'
    tool = 'tool'


class Message(BaseModel):
    """
    A single message in a conversation. Deliberately close to the
    OpenAI / Anthropic chat message format so drivers don't have to
    re-shape on every hop.

    """

    role: Role
    content: str | None = Field(
        None,
        description='Message text. Text-only for now; multimodal extensions\ndeferred. **Nullable, and no longer required:** an assistant\nturn that only calls a tool has no text to carry, and the\nalternative — an empty string — would assert the model said\nnothing when in fact it said something that was not text.\n',
    )
    toolCalls: list[dict[str, Any]] | None = Field(
        None,
        description="On an **assistant** message: the tool calls the model made,\nin OpenAI's `{id, type, function: {name, arguments}}` shape.\n\nDeliberately loose here. This is the *shared* schema, so a\ntightly-typed copy would be a third definition of the same\nobject alongside the gateway's and the driver's, and the one\nplace all three must agree is the wire format, which is\nOpenAI's and not ours to restate. The two API documents\ncarry the strict shapes.\n",
    )
    toolCallId: str | None = Field(
        None,
        description='On a **tool** message: which call this is the result of.\n`content` is the result, serialized by the caller.\n',
    )
    timestamp: AwareDatetime | None = Field(
        None, description='When the message was produced. Server-assigned if omitted.'
    )


class BackendKind(StrEnum):
    """
    Which wire protocol an inference-driver instance speaks to its
    backend. Reported by the driver's `/v1/info` so the gateway can
    log it and the UI can render a label.

    `openai_compat_http` covers every local engine we care about
    (llama.cpp's `llama-server`, vLLM, LM Studio, Ollama) as well as
    hosted OpenAI-compatible services — the protocol is shared even
    though the providers are not, so `DriverInfo.provider` is what
    distinguishes them. `claude_code_cli` and `codex_cli` shell out
    to the respective CLIs, which is how a subscription the operator
    already pays for becomes just another backend.

    """

    anthropic_api = 'anthropic_api'
    openai_api = 'openai_api'
    claude_code_cli = 'claude_code_cli'
    codex_cli = 'codex_cli'
    openai_compat_http = 'openai_compat_http'


class ComponentKind(StrEnum):
    """
    Which Eugene Plexus component class a topology entry
    represents. Lives in `common.yaml` because more than one
    component references it: the agent's `/v1/components`, and
    (via `ConfigField.componentKindHint`) any component declaring
    a config field that points at a peer of a specific kind.

    A component is a **Eugene Plexus process**. Engine processes
    are not components and are not named here — they are runtimes,
    declared separately on the agent, because a third-party
    binary shares none of a component's declarative shape (no
    module, no config trio, no service token). See the agent's
    `GET /v1/runtimes`.

    `control` is the trust root, node registry, install-wide
    topology and UI host — exactly one active, plus warm standbys.
    `gateway` is the one OpenAI-compatible front door and there is
    exactly one. `inference-driver` instances are the per-backend
    wrappers and there are N — one per backend, wherever that
    backend lives. `library` scans the operator's model
    directories and holds per-model launch profiles; there is
    exactly one, and it is deliberately not in the request path.

    **The agent is not in this list**, for the same reason engine
    runtimes are not: it supervises, it is not supervised. Its
    lifecycle belongs to the platform — a systemd unit, a container
    entrypoint — not to a topology entry. `control` *is* in the list
    precisely because the agent on its host supervises it like
    anything else, which is what stops the control root needing a
    second copy of the supervision machinery.

    """

    control = 'control'
    gateway = 'gateway'
    inference_driver = 'inference-driver'
    library = 'library'


class ComputeDeviceKind(StrEnum):
    """
    What kind of device this is.

    A named schema rather than an inline enum because an inline one
    generated a bare `Kind` class, which is too generic to sit in a
    module every component imports.

    Note `cpu` is a member, which is why the surrounding schema is
    `ComputeDevice` and not `Accelerator`: a list that includes CPUs
    is a device list. The narrower `HostAccelerator.accelerator` on
    the agent keeps its own name and its own values — it answers
    "which prebuilt engine build fits this machine", not "what can
    this host compute on".

    """

    cuda = 'cuda'
    rocm = 'rocm'
    xpu = 'xpu'
    metal = 'metal'
    cpu = 'cpu'


class EngineKind(StrEnum):
    """
    Which engine adapter constructs the argv and interprets
    readiness. Deliberately a closed enum rather than a free string:
    an engine is supported exactly when an adapter exists for it,
    and without an adapter there is nothing that knows how to start
    it or tell when it is ready.

    `llama_cpp` drives upstream `llama-server` and loads GGUF.
    `vllm` drives upstream `vllm serve` and loads safetensors. MLX
    is a third adapter later. We never ship an engine — every one of
    them is an upstream project we wrap and track.

    The two differ in far more than argv, and that is why readiness
    is per-adapter rather than one shared TCP check:
    `llama-server` answers `/health` while it loads and reports that
    it is loading, whereas vLLM binds its port *before* loading the
    model and refuses connections until the model is in memory — so
    for minutes it is indistinguishable, over the network alone,
    from a process that died. They differ in acquisition too: a
    llama.cpp build is fetched and verified by us, while vLLM is a
    Python package the operator installs themselves. See
    `EngineAcquisition.policy`.

    Lives here rather than on the agent because two components
    reference it: the agent's engines and runtimes, and a
    library `ModelProfile`, which names the engine its launch flags
    are written for.

    """

    llama_cpp = 'llama_cpp'
    vllm = 'vllm'


class ModelFormat(StrEnum):
    """
    On-disk format of a model. A dimension of the data model rather
    than an assumption (locked 2026-09-08): both are implemented at
    v0.1, and the differences are load-bearing rather than
    cosmetic.

    * `gguf` — a single file, quantized, carrying its own metadata
      and tokenizer. Large models may be **split** into
      `…-00001-of-0000N.gguf` shards, of which only the first is
      named on a launch line. A multimodal GGUF ships its vision
      projector as a separate file in the same directory, which is
      not itself a model.
    * `safetensors` — a directory: `config.json` plus one or more
      weight files plus tokenizer files. Unquantized in practice,
      so **no quant tier** — a safetensors model is sized, not
      tiered, and the quant fields exist only on the GGUF side.

    Shared because it appears on both sides of a join: a library
    entry declares what a model *is*, and
    `EngineDescriptor.modelFormats` declares what an engine can
    *load*. Nothing can serve a safetensors model until the vLLM
    adapter lands, and that answer comes from the engine's
    descriptor rather than from anything the library knows.

    """

    gguf = 'gguf'
    safetensors = 'safetensors'


class Problem(BaseModel):
    """
    Error response shape, modeled on RFC 7807 (problem+json). Every
    Eugene Plexus component returns this for 4xx / 5xx responses.

    """

    type: str = Field(
        ...,
        description='A URI reference identifying the problem type, per RFC 7807.\nModeled as a plain string rather than `format: uri` to keep\nsentinel values like `about:blank` and ergonomic at call sites.\n',
    )
    title: str = Field(..., description='Short human-readable summary.')
    status: int = Field(..., description='HTTP status code.')
    detail: str | None = Field(
        None, description='Human-readable explanation specific to this occurrence.'
    )
    instance: str | None = Field(
        None,
        description='A URI reference identifying the specific occurrence. Modeled\nas a plain string for the same reason as `type`.\n',
    )
    component: str | None = Field(
        None,
        description='Eugene Plexus component name that originated the error\n(e.g. `"gateway"`, `"inference-driver:left"`).\n',
    )


class Status(StrEnum):
    ok = 'ok'
    degraded = 'degraded'
    error = 'error'


class Health(BaseModel):
    """
    Liveness / readiness response shape.
    """

    status: Status
    version: str | None = Field(None, description='Component version (semver).')
    component: str | None = Field(
        None, description='Component identifier (e.g. `"inference-driver"`).'
    )
    safeMode: bool | None = Field(
        False,
        description="True when the component was started with the agent's\nsafe-mode env var set\n(`EUGENE_PLEXUS_<KIND>_SAFE_MODE=1`) and is therefore\nrunning on built-in defaults instead of its persisted\nconfig. Components in safe mode are reachable for config\nediting (`PATCH /v1/config` writes to disk normally) but\nshould be considered non-functional for their primary\npurpose until restarted without the flag. `status` is\nalso reported as `degraded` while safe mode is in effect.\n",
    )
    details: dict[str, Any] | None = Field(
        None, description='Optional component-specific health detail.'
    )


class ConfigValueType(StrEnum):
    """
    The kind of value a config field holds. The UI uses this to pick
    a renderer (text input, dropdown, password field, etc.).

    Three of these hold more than a scalar. `path_list` is an
    ordered JSON array of directory paths on the component host —
    the library's model roots are the first and so far only user —
    and the UI renders it as an add/remove list of directory pickers
    rather than a text field, because asking someone to
    comma-separate Windows paths is asking for a bug report. Order
    is preserved and meaningful: it is the order the operator sees,
    and M3's downloader offers the first entry as the default
    destination.

    `url_list` is the same argument one type over: an ordered JSON
    array of URLs, rendered as an add/remove list of address fields.
    Added at M5 for the control root's standby endpoints, which are
    inherently plural — *"N standbys is a configuration, not a
    mechanism"* — and which have no natural single-value spelling.
    A comma-separated text field would be the same bug report
    `path_list` exists to avoid, and reusing `path_list` for
    addresses would tell every UI to open a directory picker.
    Validation is the field's business rather than the type's; what
    the type promises is a list whose entries are addresses.

    `runtime_name` holds the `name` of a supervised engine runtime,
    and UIs render it as a dropdown sourced from the agent's
    `GET /v1/runtimes`. It exists because `componentKindHint` cannot
    do this job: a runtime is deliberately not a component, so
    `/v1/components` does not list one. What is saved is the
    runtime's *name*, never its URL — the agent assigns the port
    when the operator does not pick one, so a stored URL would
    encode a number the operator never chose and does not own, and
    would be wrong the moment the runtime moved. Its first user is
    the inference-driver's `runtimeName`, which is how a driver
    follows the engine process it fronts.

    `node_name` holds the `name` of an enrolled node, rendered as a
    dropdown sourced from the control root's `GET /v1/nodes`. Same
    reasoning as `runtime_name` one level up: a node is not a
    component either, so `componentKindHint` cannot source it, and
    what is saved is the name rather than a URL because the address
    of a host is topology the control root owns.

    `model_slots` is the gateway's priority-list surface, and the
    one value here that holds objects. An ordered JSON array of
    `{"model": <alias a client asks for>, "targets": [<model id>,
    ...]}`: a request for `model` is served by the drivers serving
    `model` itself, then by the drivers serving each target in
    order, cascading on failure. Targets are **model ids, not driver
    names**, because a model id names a replica set — every driver
    currently serving it, load-balanced — and a driver name would
    name one process. That is why the value reserved since M2 as
    `driver_list` was renamed when M6 defined it: the old name said
    the wrong thing about what goes in the list. A cloud
    subscription is a target like any other, because a
    `claude_code_cli` driver already serves a model id. UIs without
    a structured renderer for it fall back to editing the JSON.

    `path_mappings` (M11) is an ordered JSON array of `PathMapping`
    — `{"from": <a directory as another machine states it>, "to":
    <the same directory on this host>}`. Its one user is the agent's
    `pathMappings`, which is how a node opens model files a library
    on another host described by *its* path: `/models` on the NAS
    is `Z:\\models` here. UIs render it as rows of two directory
    fields, the right-hand one browsable on the component's own
    host, and offer the library's configured roots as suggestions
    for the left. Matching, precedence and translation rules are on
    the agent's field description, not here — the type promises a
    list of pairs and nothing about what they mean.

    """

    string = 'string'
    integer = 'integer'
    number = 'number'
    boolean = 'boolean'
    enum = 'enum'
    secret = 'secret'
    file_path = 'file_path'
    path_list = 'path_list'
    url = 'url'
    url_list = 'url_list'
    duration = 'duration'
    runtime_name = 'runtime_name'
    node_name = 'node_name'
    model_slots = 'model_slots'
    path_mappings = 'path_mappings'


class ConfigFieldShowWhen(BaseModel):
    """
    Predicate over another `ConfigField`'s current value. The UI
    renders the field this is attached to only when the named field
    equals the given value (or matches one entry in the given list).

    """

    key: str = Field(
        ...,
        description='`key` of another field in the same `ConfigSchema` to compare\nagainst.\n',
    )
    equals: Any = Field(
        ...,
        description="Value the named field must equal for this field to render.\nUntyped — when scalar, matches by literal equality against\nthe referenced field's `valueType`. When an array, matches\nif the referenced field's current value equals any entry\n(set-membership). Use the array form for a field that\napplies to multiple entries of an enum (e.g. an `apiKey`\nfield shared across several OpenAI-compatible providers).\n",
    )


class ConfigDocument(BaseModel):
    """
    Current effective config values, keyed by `ConfigField.key`.
    Values of fields with `sensitive: true` are returned as the
    literal string `"<redacted>"` regardless of whether they are
    set. Returned by `GET /v1/config`.

    """

    model_config = ConfigDict(
        extra='allow',
    )


class ConfigUpdateRequest(BaseModel):
    """
    Partial update for `PATCH /v1/config`. Every present key is
    set; absent keys are left unchanged. To revert a field to its
    default, send `null` as the value. Sensitive fields are written
    through directly (the redacted form sent back by GET is never
    accepted as a write value).

    """

    model_config = ConfigDict(
        extra='allow',
    )


class ConfigFieldError(BaseModel):
    """
    A per-field validation failure during PATCH.
    """

    key: str
    message: str


class ConfigUpdateResult(BaseModel):
    """
    Outcome of a `PATCH /v1/config` call. Validation failures on
    individual keys do not abort the whole request — valid changes
    are applied, invalid ones are reported in `rejected`.

    """

    applied: list[str] = Field(
        ..., description='Keys that were validated and applied successfully.'
    )
    rejected: list[ConfigFieldError] = Field(
        ...,
        description='Keys whose new values failed validation. The current value\nis preserved.\n',
    )
    requiresRestart: bool = Field(
        ...,
        description='True if any key in `applied` has `requiresRestart: true`,\nmeaning a process restart is needed for the change to take\neffect. The UI should surface this to the user.\n',
    )
    pendingRestart: list[str] | None = Field(
        None,
        description='Keys whose new values are stored but not yet active. Subset\nof `applied`. Empty unless `requiresRestart` is true.\n',
    )


class ConfigTestRequest(BaseModel):
    """
    Optional override for `POST /v1/config/test`. Same shape as
    `ConfigUpdateRequest`: keys override the saved config for the
    duration of the test only. Useful for "Test Connection" UIs where
    the operator wants to verify a new API key, URL, or model
    identifier before committing it. Send an empty body (`{}`) to
    test the saved config as-is.

    """

    overrides: ConfigUpdateRequest | None = None


class ConfigTestResult(BaseModel):
    """
    Result of a `POST /v1/config/test` invocation. Components decide
    what "test" means for their own surface: an inference-driver runs
    a minimal `generate()` round-trip against its backend; the
    gateway probes every driver it can route to; the library checks
    that its configured model directories are readable.

    """

    ok: bool = Field(
        ..., description='True iff the test invocation succeeded end-to-end.'
    )
    component: str = Field(
        ...,
        description='Component identifier (matches `ConfigSchema.component`).\nEchoed for UI clarity when several /v1/config/test responses\nland in the same view.\n',
    )
    latencyMs: int = Field(
        ..., description='Wall-clock time the test took, in milliseconds.'
    )
    summary: str | None = Field(
        None,
        description='One-line human-readable result summary. Always set when\n`ok` is true; may be set on failure to add context beyond\n`error`.\n',
    )
    sampleOutput: str | None = Field(
        None,
        description="Brief sample of the data the test produced — e.g. assistant\ntext from an inference-driver `generate()` round-trip. May be\ntruncated to keep the response small. Omitted when there's\nnothing useful to show.\n",
    )
    error: str | None = Field(
        None,
        description='Human-readable error message. Set when `ok` is false. Should\nbe specific enough that the operator can act on it (e.g.\n`"openaiApiKey rejected: 401 Unauthorized"`).\n',
    )


class SecurityMode(StrEnum):
    """
    Operator's choice for how the agent handles its master key
    between restarts. Set during the wizard's security screen; can
    be changed later from the Config page.

    * `prompt_on_startup` — passphrase required at every agent
      start. Master key lives only in process memory. Best for
      shared environments, sensitive conversations, security-
      conscious operators. A power outage means Eugene stays
      offline until the operator re-enters the passphrase.
    * `os_keyring` — master key stored in the OS secret store
      (Windows Credential Manager / macOS Keychain / Linux Secret
      Service via the `keyring` Python lib). OS unlocks tied to
      user login; Eugene auto-recovers from restarts. Best for
      home / personal-use installs and anyone who wants minimum
      friction. Anyone with the OS account can also start Eugene.

    """

    prompt_on_startup = 'prompt_on_startup'
    os_keyring = 'os_keyring'


class AuthLoginRequest(BaseModel):
    """
    Login request body sent by the UI to `POST /v1/auth/login` on
    the agent. The passphrase is the same one the operator set
    in the wizard. The agent bcrypt-compares it; on match,
    issues a session token.

    """

    passphrase: str = Field(..., min_length=1)


class AuthLoginResponse(BaseModel):
    """
    Issued on successful login. The UI stores `sessionToken` as a
    Secure / HttpOnly / SameSite=Strict cookie or in memory; every
    subsequent proxy request includes it as
    `Authorization: Bearer <token>`.

    """

    sessionToken: str = Field(
        ...,
        description='Opaque bearer token. Signed and validated server-side; the\nUI should never inspect its contents. Lifetime is bounded\nby `expiresAt`.\n',
    )
    expiresAt: AwareDatetime
    operatorName: str | None = Field(
        None,
        description='The operator\'s display name from the constitution\n(typically "operator" or whatever the operator set).\nEchoed for UI welcome strings.\n',
    )


class Alg(StrEnum):
    """
    Encryption algorithm identifier.
    """

    secretbox_xsalsa20poly1305 = 'secretbox-xsalsa20poly1305'


class MasterKeyEnvelope(BaseModel):
    """
    Encrypted-at-rest envelope for sensitive config fields. The
    on-disk YAML for fields marked `sensitive: true` is stored as
    this envelope when v0.2 security is enabled; the component
    decrypts using the master key passed in by the agent at
    spawn time (env var `EUGENE_PLEXUS_<KIND>_MASTER_KEY`,
    base64-encoded).

    Algorithm: libsodium secretbox (XSalsa20-Poly1305). The nonce
    is generated per-encryption and stored alongside the
    ciphertext. The master key is 32 bytes derived from the
    operator's passphrase via Argon2id with parameters chosen at
    first-run time and persisted in the agent's state.

    Components MAY accept plaintext values in PATCH requests
    (current behavior); on persist, they encrypt to this envelope
    if the master key is available. GET requests continue to
    return `"<redacted>"` for sensitive fields regardless of
    envelope-vs-plaintext on disk.

    """

    alg: Alg = Field(..., description='Encryption algorithm identifier.')
    nonce: str = Field(
        ...,
        description='Base64-encoded 24-byte nonce. Generated per-encryption,\nnever reused with the same key.\n',
    )
    ciphertext: str = Field(..., description='Base64-encoded ciphertext + auth tag.')


class RestartResult(BaseModel):
    """
    Acknowledgement returned by `POST /v1/admin/restart`. The
    component schedules its own process exit shortly after returning
    this response (typically a few hundred ms — long enough for the
    HTTP response to flush). The component does NOT bring itself
    back up; a process supervisor (systemd, docker-compose, the
    deploy launcher, etc.) is expected to relaunch it. In v0.1
    personal-use deploys without a supervisor, the operator
    relaunches manually.

    """

    scheduled: bool = Field(
        ...,
        description='True if the component accepted the restart and an exit is\nqueued. Always true in v0.1 — the endpoint has no reason to\nrefuse — but typed as a boolean so future versions can gate\non (e.g.) an in-flight long-running operation.\n',
    )
    delayMs: int = Field(
        ...,
        description='How long the component intends to wait before calling exit,\nmeasured from the moment the response is sent. Lets clients\ntime their UI ("restarting in 0.5s…") and decide when to\nstart polling `/healthz` for the relaunched process.\n',
        ge=0,
    )
    message: str | None = Field(
        None,
        description='Optional human-readable note (e.g. "logs flushed, exiting\nnow"). UI may display this in the restart-progress dialog.\n',
    )


class PathMapping(BaseModel):
    """
    One rule for reading a path that another machine wrote.

    The library describes each model by its path **on the library's
    own host**, and a runtime declaration copies that string
    verbatim — so when the engine runs elsewhere, the agent there is
    handed a path from a filesystem it does not have. A mapping says
    where the same directory is on this host: the NAS's `/models`
    is `Z:\\models` on the Windows box that mounts it. Nothing is
    copied or cached; the operator mounts the share, and this tells
    the agent where they mounted it.

    Shared here because it appears in two places on the agent: as
    the entries of the `pathMappings` config field, and as
    `ModelLocation.mapping` on an admission answer, which reports
    the rule that applied. Two definitions of one pair would drift.

    """

    from_: str = Field(
        ...,
        alias='from',
        description="A directory as the other machine states it — in practice a\nlibrary root, spelled exactly as the library's own\n`GET /v1/config` lists it. Its shape decides how it matches:\na drive letter or UNC prefix means Windows rules (case-\ninsensitive, `/` and `\\` interchangeable); a leading `/`\nmeans POSIX rules. The agent cannot know the library's\noperating system, and the string came from it, so the\nstring stands in.\n",
    )
    to: str = Field(
        ...,
        description="The same directory on the host holding this config. Used\nverbatim, `~` expanded; the remainder of a matched path is\nre-joined onto it with this host's own separator.\n",
    )


class DirectoryEntryKind(StrEnum):
    """
    Files appear only when a listing asked for `includeFiles`. A
    directory picker never does; a `file_path` field's picker would,
    which is why the flag exists on the endpoint without a UI yet.

    """

    directory = 'directory'
    file = 'file'


class FinishReason(StrEnum):
    stop = 'stop'
    length = 'length'
    stop_sequence = 'stop_sequence'
    tool_calls = 'tool_calls'
    error = 'error'


class FunctionDefinition(BaseModel):
    name: str
    description: str | None = None
    parameters: dict[str, Any] | None = Field(
        None, description='A JSON Schema object, passed through verbatim.'
    )
    strict: bool | None = None


class Function(BaseModel):
    name: str


class NamedToolChoice(BaseModel):
    type: Literal['function']
    function: Function


class FunctionCall(BaseModel):
    name: str
    arguments: str = Field(
        ...,
        description='Arguments as a JSON **string**, not an object — a model can\nemit invalid JSON and the string preserves what it actually\nsaid. Not parsed here.\n',
    )


class Function1(BaseModel):
    name: str | None = None
    arguments: str | None = None


class ToolCallDelta(BaseModel):
    index: int
    id: str | None = None
    type: Literal['function'] = 'function'
    function: Function1 | None = None


class Type(StrEnum):
    text = 'text'
    json_object = 'json_object'
    json_schema = 'json_schema'


class ResponseJsonSchema(BaseModel):
    name: str
    description: str | None = None
    schema_: dict[str, Any] = Field(..., alias='schema')
    strict: bool | None = None


class Usage(BaseModel):
    """
    Token accounting. Some backends (CLI subprocess) may report nulls.
    """

    promptTokens: int | None = Field(None, ge=0)
    completionTokens: int | None = Field(None, ge=0)
    totalTokens: int | None = Field(None, ge=0)


class EmbedRequest(BaseModel):
    """
    Text to embed. Batched because every backend that does this
    accepts a batch, and a per-item round trip would multiply the
    control plane's own overhead by the size of a document set.

    """

    input: list[str] = Field(
        ...,
        description='One entry per vector to produce. Order is preserved: the\nn-th vector in the response is the n-th input, which is the\nonly thing that lets a caller match them up, since an\nembedding carries no identity of its own.\n',
        min_length=1,
    )
    requestId: str | None = Field(
        None,
        description='Correlation id, echoed back. Same role as on `GenerateRequest`.',
    )


class EmbedResponse(BaseModel):
    embeddings: list[list[float]] = Field(
        ...,
        description='One vector per input, in the order the inputs arrived.\nFloats, always — see the operation description for why this\nsurface does not carry base64.\n',
    )
    modelId: str | None = Field(
        None,
        description="The model that produced these vectors, as the backend named\nit. **Load-bearing beyond attribution:** vectors from two\nmodels are not comparable, so a caller storing them needs to\nknow which model's space they belong to.\n",
    )
    backend: BackendKind | None = None
    usage: Usage | None = None
    latencyMs: int | None = Field(None, ge=0)
    requestId: str | None = None


class Capabilities(BaseModel):
    """
    Backend capabilities the gateway keys off when routing.
    """

    streaming: bool | None = Field(
        None, description='Whether `/v1/generate/stream` emits true incremental tokens.'
    )
    toolCalling: bool | None = Field(
        None,
        description='Whether this driver can carry `tools` to its backend and\nreport `toolCalls` back.\n\nThe gateway reads it to answer a question a harness\ncannot otherwise ask: a plain answer where a tool call\nwas expected looks identical whether the model declined\nor the backend never saw the tools. A driver that says\n`false` here is failed at the front door with a reason\ninstead.\n',
    )
    embeddings: bool | None = Field(
        None,
        description='Whether this driver can serve `POST /v1/embed`.\n\n**A property of the running backend, not of the model**,\nand not readable from anything: `llama-server`\'s\n`/props` carries no pooling or embedding field, and an\nOllama runner started for chat refuses with "This server\ndoes not support embeddings". So it is determined by\ntrying once and cached for the driver\'s lifetime — which\nis the right lifetime, since it cannot change without\nthe backend restarting.\n\nThe gateway reads it to mark which surface each model\nserves on `GET /v1/models`, and to refuse a chat request\nagainst an embeddings-only model with a reason instead\nof passing it down to fail obscurely.\n',
    )
    maxContextTokens: int | None = Field(
        None,
        description="The context window the backend **resolved**, read back\nfrom the backend itself — not the model's trained\nmaximum, and never an estimate.\n\nNull means unknown, and unknown is a real answer: a\nhosted provider exposes nothing to read, and a CLI\nsubscription has no window of its own to report. The\ngateway's `_smallest_context` folds this together with\nthe window a supervised runtime reports and publishes\nthe smallest as `x_eugene_plexus.context_length` on\n`GET /v1/models`, so a harness can size a prompt\nagainst the number that will actually apply.\n\n**Populated by a probe of the backend, which is why it\nexists at all.** A supervised runtime already tells the\nagent its window; this field is for the backend nobody\nsupervises — an Ollama or an LM Studio the operator\npoints us at — which until now reported no window\nanywhere. Contracted since M0 and populated by nothing\nuntil then, exactly as `streaming` was until M10.\n\n**Advertising, not enforcement.** Nothing here counts a\nprompt: the window is published so a caller can respect\nit, and a caller that does not is refused by the engine\nitself, whose count is exact. A backend that truncates\nsilently instead of refusing is caught after the fact —\nsee `x_eugene_plexus.prompt_truncated` in\n`gateway.yaml`.\n",
        ge=0,
    )


class DriverInfo(BaseModel):
    """
    Driver self-description, and the gateway's only source of truth
    for what this backend serves. A driver does not know its position
    in any topology: its operator-supplied name lives in the agent
    topology, not here.

    """

    backend: BackendKind
    provider: str | None = Field(
        None,
        description='Operator-friendly provider key from the driver\'s\nregistry (e.g. `"openai"`, `"xai"`, `"openrouter"`,\n`"claude_subscription"`). Reflects which subscription /\nservice this driver is wrapping — `backend` reflects the\n*protocol* underneath, which can be shared across many\nproviders (e.g. xAI, OpenRouter, Ollama all report\n`backend: openai_compat_http`). Optional; omitted when\nthe driver is in degraded mode and never finished\nconstructing.\n',
    )
    modelId: str | None = Field(
        None,
        description='Backend-specific model identifier (e.g. `"claude-opus-4-7"`).\nOptional — omitted when the driver is configured to use the\nadapter\'s built-in default rather than pinning a specific model.\n',
    )
    runtime: str | None = Field(
        None,
        description="The supervised engine runtime this driver is following, when\nit was configured with `runtimeName` rather than a literal\n`baseUrl`. Absent for a cloud provider, a CLI subscription,\nor any backend that is not a runtime this install\nsupervises.\n\nReported here despite the rule that a driver never says\nwhere it sits, because this is not the driver's own address —\nit is *what it serves*, which is exactly what `/v1/info` is\nfor. It lets the gateway and the UI show which engine\nprocess is behind a driver, so a model that is loaded but\nunroutable is diagnosable from the routing table instead of\nby reading two components' configs side by side.\n",
    )
    capabilities: Capabilities | None = Field(
        None, description='Backend capabilities the gateway keys off when routing.'
    )
    version: str | None = Field(None, description='inference-driver semver.')


class ComputeDevice(BaseModel):
    """
    One compute device on one host, as that host's agent detected it.

    Shared because it appears on both sides of a join: an agent
    reports its own devices on `GET /v1/node`, and the control root
    aggregates them into `Node.devices` — the cross-host
    inventory M3 deferred with the note that *"building a real
    inventory is topology work"*. Two copies of this shape would be
    two definitions of one fact, and the copy would be the one that
    went stale.

    Deliberately **not** the same thing as the agent's
    `HostAccelerator`, which answers a narrower question — "which
    prebuilt engine build should we fetch for this machine" — and
    describes a host in the singular. This is a device *list*,
    because a host with two cards is the case that makes replicas of
    one model possible.

    """

    kind: ComputeDeviceKind
    name: str | None = Field(
        None,
        description='Device name as the vendor reports it, e.g. `NVIDIA GeForce RTX 5090`.',
    )
    index: int | None = Field(
        None,
        description="Device ordinal on its own host — what `CUDA_VISIBLE_DEVICES`\nor `HIP_VISIBLE_DEVICES` in a runtime's `env` selects to pin\nthat runtime to one card.\n",
        ge=0,
    )
    memoryTotalBytes: int | None = None
    memoryFreeBytes: int | None = Field(
        None,
        description='Free decides whether a model fits, not total — M3 measured\n2.9 GiB of a 32 GiB card already held on an idle desktop.\nBoth are reported so the difference is visible rather than\nsurprising.\n',
    )


class ConfigField(BaseModel):
    """
    UI-renderable description of a single editable config field.

    """

    key: str = Field(
        ...,
        description='Stable machine-readable id, dot-separated for grouping\n(e.g. `"adapter.modelId"`).\n',
    )
    label: str = Field(..., description='Human-readable label for the UI.')
    description: str | None = Field(
        None, description='One-sentence explanation suitable for non-programmers.'
    )
    category: str = Field(
        ...,
        description='Group key for UI tabbing or sectioning (e.g. `"adapter"`,\n`"logging"`, `"network"`). Mapped to a display label via\n`ConfigSchema.categories`.\n',
    )
    valueType: ConfigValueType
    default: Any | None = Field(
        None,
        description='Default value if unset. Type matches `valueType`. Omitted\nfor fields with no default.\n',
    )
    enumValues: list[str] | None = Field(
        None, description='Allowed values when `valueType == enum`.'
    )
    suggestions: list[str] | None = Field(
        None,
        description="Discovery-time hints — values the operator might want\nbut which AREN'T enforced by validation. UIs render\nstring-typed fields with non-empty `suggestions` as a\ncombobox (free-text input with a dropdown of suggestions)\nrather than a strict dropdown. Use when the set of\nvalid values is large, partially-discoverable, or\nextends beyond what the component knows at the moment\n(e.g. local LLM model lists that update when the operator\npulls a new model). Distinct from `enumValues`:\nsuggestions are advisory, enumValues are mandatory.\n",
    )
    componentKindHint: ComponentKind | None = Field(
        None,
        description="Declarative rendering hint: this field references a peer\ncomponent of the given kind. UIs render any kind-hinted\nfield as a dropdown sourced from the agent's\n`/v1/components` (filtered by kind), with `(off)` as the\nfirst option (saves an empty string). For single-instance\nkinds (memory, identity, etc.) the dropdown UX collapses\nto effectively a toggle; for multi-instance kinds\n(inference-driver) the operator picks one. Pairs with a\nstring/url `valueType` — the saved value is still the\npeer's URL, the hint only changes how the UI looks it up.\nAvoids the OpenClaw trap of duplicating topology into\nfree-text URL fields the operator has to type by hand.\n",
    )
    enumLabels: list[str] | None = Field(
        None,
        description='Optional human-readable display labels paired one-to-one\nwith `enumValues`. UIs that render an enum as a dropdown\nshould show `enumLabels[i]` while still submitting\n`enumValues[i]` as the saved value. When omitted (or\nshorter than `enumValues`), UIs fall back to the raw\nvalue as the label. Useful where the stored key is\nmachine-friendly but the user-facing label isn\'t —\ne.g. `claude_subscription` saved, "Claude (Pro/Max)"\nshown.\n',
    )
    sensitive: bool | None = Field(
        False,
        description='If true, the value is redacted (`"<redacted>"`) in\n`ConfigDocument` responses but is accepted in\n`ConfigUpdateRequest`. Use for API keys, passwords, etc.\n',
    )
    required: bool | None = Field(
        False,
        description='If true, the component will refuse to start without this\nfield set (either in config or via env var fallback).\n',
    )
    minimum: float | None = Field(
        None, description='Validation hint for `integer` / `number` fields.'
    )
    maximum: float | None = Field(
        None, description='Validation hint for `integer` / `number` fields.'
    )
    pattern: str | None = Field(
        None, description='Regex validation hint for `string` / `url` / `file_path`.'
    )
    requiresRestart: bool | None = Field(
        False,
        description='If true, changes to this field via PATCH are accepted and\nstored but do not take effect until the component process\nrestarts. The UI should warn before submitting.\n',
    )
    showWhen: ConfigFieldShowWhen | None = Field(
        None,
        description="Conditional-rendering hint. When set, the UI should only\nrender this field when another field's current value matches\nthe condition. Used to hide adapter-specific fields\n(e.g. `openaiApiKey`) when a different adapter is selected.\nThe component still validates and stores the field\nregardless of UI visibility.\n",
    )


class ConfigSchema(BaseModel):
    """
    UI-renderable description of every editable config field this
    component accepts. Returned by `GET /v1/config/schema`. UIs use
    this to render a generic config editor without component-specific
    code.

    """

    component: str = Field(
        ..., description='Component identifier (e.g. `"inference-driver"`).'
    )
    fields: list[ConfigField]
    categories: dict[str, str] | None = Field(
        None,
        description='Map from category key (used in `ConfigField.category`) to\na human-readable section label. Optional; UIs may fall back\nto the raw key.\n',
    )


class DirectoryEntry(BaseModel):
    name: str
    path: str = Field(
        ..., description='Absolute path, ready to be used as a config value.'
    )
    kind: DirectoryEntryKind
    hidden: bool | None = Field(
        False,
        description='A dot-prefixed name, or the hidden attribute on Windows.\nOnly present in a listing that asked for `showHidden`.\n',
    )


class StreamToken(BaseModel):
    """
    One `event: token` payload. Exactly one of `text` or `toolCalls`
    is set.

    """

    text: str | None = Field(None, description="A fragment of the assistant's text.")
    toolCalls: list[ToolCallDelta] | None = Field(
        None,
        description='Fragments of one or more tool calls, accumulated by `index`.\n',
    )


class Tool(BaseModel):
    type: Literal['function']
    function: FunctionDefinition


class ToolCall(BaseModel):
    id: str
    type: Literal['function']
    function: FunctionCall


class ResponseFormat(BaseModel):
    type: Type
    json_schema: ResponseJsonSchema | None = None


class GenerateRequest(BaseModel):
    messages: list[Message] = Field(
        ...,
        description='Full prompt as an ordered conversation. Whatever system\nmessage the caller wants is already in here; the driver does\nnot modify, prepend to, or reorder it.\n',
    )
    maxTokens: int | None = Field(
        None,
        description="Maximum output tokens. Backend-clamped. Owned by the caller\n(the gateway) — the driver applies no local default. Adapters\nwhose backends don't expose this knob (agentic CLIs) ignore\nit silently.\n",
        ge=1,
    )
    temperature: float | None = Field(
        None,
        description="Sampling temperature. Backend-clamped. Owned by the caller\n(the gateway, which resolves it from the model's settings\nprofile) — the driver applies no local default. Backends that\nreject the parameter outright, as some reasoning models do,\nhave it dropped with a warning rather than erroring.\n",
        ge=0.0,
        le=2.0,
    )
    stop: list[str] | None = Field(None, description='Optional stop sequences.')
    requestId: UUID | None = Field(
        None,
        description='Caller-supplied id for log correlation. Echoed in the response.',
    )
    tools: list[Tool] | None = Field(
        None,
        description="Tools the model may call, in OpenAI's shape. Carried down to\nthe backend unchanged and never executed here — the driver\nis a protocol adapter, and running a tool is the caller's\njob by the same reasoning that keeps output-affecting\nparameters on the gateway.\n\nAn adapter whose backend cannot carry tools MUST fail the\nrequest rather than drop the field. Dropping it yields a\nplain answer that a harness cannot distinguish from the\nmodel declining to call anything.\n",
    )
    toolChoice: ToolChoice | NamedToolChoice | None = Field(
        None,
        description='`none`, `auto`, `required`, or an object naming one\nfunction. Passed through.\n',
    )
    responseFormat: ResponseFormat | None = None


class DirectoryListing(BaseModel):
    """
    One directory on the component's own host, listed for a picker.

    Returned by `GET /v1/directories` on the library (whose host
    holds the model roots) and on the agent (whose host holds a
    path mapping's `to`, and any engine binary an operator points
    at). The same shape on both, because the UI has one picker and
    the only thing that differs is which machine's disk it is
    looking at — which is why `host` is on the response.

    This is the endpoint behind the promise `path_list` has carried
    since M2: *"an add/remove list of directory pickers"*. It lists
    what an operator could already type into a path field, on
    request, to the strongest credential there is; it is not a new
    capability and it is not a file browser.

    """

    host: str = Field(
        ...,
        description='The machine whose disk this is. On a multi-host install the\nanswer to "browse" is frequently a machine other than the\none the browser is on.\n',
    )
    path: str | None = Field(
        None,
        description='The directory listed, absolute and as this host spells it.\nAbsent when no `path` was asked for, in which case `entries`\nare the places to start from — every drive on Windows, `/`\non POSIX, and the home directory.\n',
    )
    parent: str | None = Field(
        None,
        description='The directory above `path`, so a picker can go up without\ndoing path arithmetic in a browser. Absent at a filesystem\nroot and when `path` is absent.\n',
    )
    entries: list[DirectoryEntry] = Field(
        ...,
        description='Sorted by name, directories first. Entries this component\nmay not read are omitted rather than failing the listing.\n',
    )


class GenerateResponse(BaseModel):
    content: str | None = Field(
        None,
        description='The generated assistant text. **Nullable since tool calling\nlanded:** a turn that only calls a tool produces no text,\nand an empty string would be a lie about what the model\nsaid. Was required; a response with `toolCalls` and no\n`content` is the common agent-loop case.\n',
    )
    toolCalls: list[ToolCall] | None = Field(
        None,
        description='Tools the model chose to call. Present when `finishReason`\nis `tool_calls`.\n',
    )
    finishReason: FinishReason
    usage: Usage | None = None
    requestId: UUID | None = None
    backend: BackendKind | None = None
    modelId: str | None = Field(
        None,
        description='Backend-specific model identifier (e.g. `"claude-opus-4-7"`).',
    )
    latencyMs: int | None = Field(
        None, description='End-to-end driver-side latency in milliseconds.'
    )
